/** Generated by scripts/stylex-codemod.ts from the compiled utility sheet. */
import * as stylex from "@stylexjs/stylex";
import { type as typography } from "./typography.stylex";

const sx = stylex.create({
	Bottom1: {
			bottom: "calc(4px * -1)"
	},
	Mb25: {
			marginBottom: "calc(4px * -2.5)"
	},
	Mb35: {
			marginBottom: "calc(4px * -3.5)"
	},
	Ml1: {
			marginLeft: "calc(4px * -1)"
	},
	Ml15: {
			marginLeft: "calc(4px * -1.5)"
	},
	Ml2: {
			marginLeft: "calc(4px * -2)"
	},
	Mt11px: {
			marginTop: "calc(11px * -1)"
	},
	Mx2: {
			marginInline: "calc(4px * -2)"
	},
	Mx6px: {
			marginInline: "calc(6px * -1)"
	},
	My1: {
			marginBlock: "calc(4px * -1)"
	},
	My5px: {
			marginBlock: "calc(5px * -1)"
	},
	Right1: {
			right: "calc(4px * -1)"
	},
	Rotate90: {
			rotate: "calc(90deg * -1)"
	},
	TranslateY12: {
			translate: "0 calc(calc(1 / 2 * 100%) * -1)"
	},
	TranslateYPx: {
			translate: "0 -1px"
	},
	absolute: {
			position: "absolute"
	},
	activeCursorGrabbing: {
			":active": {
					cursor: "grabbing"
			}
	},
	activeScale096: {
			":active": {
					scale: "0.96"
			}
	},
	activeScale098: {
			":active": {
					scale: "0.98"
			}
	},
	afterInsetX1: {
			"::after": {
					content: "\"\"",
					insetInline: "calc(4px * -1)"
			}
	},
	afterAbsolute: {
			"::after": {
					content: "\"\"",
					position: "absolute"
			}
	},
	afterBgAccent: {
			"::after": {
					content: "\"\"",
					backgroundColor: "var(--accent)"
			}
	},
	afterBgTransparent: {
			"::after": {
					content: "\"\"",
					backgroundColor: "transparent"
			}
	},
	afterBorderL: {
			"::after": {
					content: "\"\"",
					borderLeftStyle: "solid",
					borderLeftWidth: "1px"
			}
	},
	afterBorderTransparent: {
			"::after": {
					content: "\"\"",
					borderColor: "transparent"
			}
	},
	afterContent: {
			"::after": {
					content: "''"
			}
	},
	afterHFull: {
			"::after": {
					content: "\"\"",
					height: "100%"
			}
	},
	afterInsetY0: {
			"::after": {
					content: "\"\"",
					insetBlock: "0"
			}
	},
	afterLeft12: {
			"::after": {
					content: "\"\"",
					left: "calc(1 / 2 * 100%)"
			}
	},
	afterRight3px: {
			"::after": {
					content: "\"\"",
					right: "3px"
			}
	},
	afterRight5px: {
			"::after": {
					content: "\"\"",
					right: "5px"
			}
	},
	afterRoundedFull: {
			"::after": {
					content: "\"\"",
					borderRadius: "calc(infinity * 1px)",
					cornerShape: "round"
			}
	},
	afterSize15: {
			"::after": {
					content: "\"\"",
					width: "calc(4px * 1.5)",
					height: "calc(4px * 1.5)"
			}
	},
	afterTop0: {
			"::after": {
					content: "\"\"",
					top: "0"
			}
	},
	afterTop5px: {
			"::after": {
					content: "\"\"",
					top: "5px"
			}
	},
	afterTransitionBackground: {
			"::after": {
					content: "\"\"",
					transitionProperty: "background",
					transitionTimingFunction: "var(--tw-ease, var(--ease))",
					transitionDuration: "var(--tw-duration, var(--dur-micro))"
			}
	},
	afterTransitionColors: {
			"::after": {
					content: "\"\"",
					transitionProperty: "color, background-color, border-color, outline-color, text-decoration-color, fill, stroke, --tw-gradient-from, --tw-gradient-via, --tw-gradient-to",
					transitionTimingFunction: "var(--tw-ease, var(--ease))",
					transitionDuration: "var(--tw-duration, var(--dur-micro))"
			}
	},
	afterW2px: {
			"::after": {
					content: "\"\"",
					width: "2px"
			}
	},
	animatePulse12sEaseInOutInfinite: {
			animation: "pulse 1.2s ease-in-out infinite"
	},
	animatePulse14sEaseInOutInfinite: {
			animation: "pulse 1.4s ease-in-out infinite"
	},
	animateTextShimmer18sLinearInfinite: {
			animation: "text-shimmer 1.8s linear infinite"
	},
	animateUpdateToastInVarDurLgVarEase: {
			animation: "update-toast-in var(--dur-lg) var(--ease)"
	},
	animatePulse: {
			animation: "var(--animate-pulse)"
	},
	animateSpin: {
			animation: "var(--animate-spin)"
	},
	aspectSquare: {
			aspectRatio: "1 / 1"
	},
	aspectVideo: {
			aspectRatio: "var(--aspect-video)"
	},
	beforeInsetX35: {
			"::before": {
					content: "\"\"",
					insetInline: "calc(4px * -3.5)"
			}
	},
	beforeTop25: {
			"::before": {
					content: "\"\"",
					top: "calc(4px * -2.5)"
			}
	},
	beforeTranslateX12: {
			"::before": {
					content: "\"\"",
					translate: "calc(calc(1 / 2 * 100%) * -1) 0"
			}
	},
	beforeTranslateY12: {
			"::before": {
					content: "\"\"",
					translate: "0 calc(calc(1 / 2 * 100%) * -1)"
			}
	},
	beforeCornerShapeInherit: {
			"::before": {
					content: "\"\"",
					cornerShape: "inherit"
			}
	},
	beforeCornerShapeVarCs: {
			"::before": {
					content: "\"\"",
					cornerShape: "var(--cs)"
			}
	},
	beforeAbsolute: {
			"::before": {
					content: "\"\"",
					position: "absolute"
			}
	},
	beforeBgVarComposerNoteBg: {
			"::before": {
					content: "\"\"",
					backgroundColor: "var(--composer-note-bg)"
			}
	},
	beforeBgDivider: {
			"::before": {
					content: "\"\"",
					backgroundColor: "var(--divider)"
			}
	},
	beforeBgTransparent: {
			"::before": {
					content: "\"\"",
					backgroundColor: "transparent"
			}
	},
	beforeContent: {
			"::before": {
					content: "''"
			}
	},
	beforeDuration150: {
			"::before": {
					content: "\"\"",
					transitionDuration: "150ms"
			}
	},
	beforeEaseCubicBezier03207201: {
			"::before": {
					content: "\"\"",
					transitionTimingFunction: "cubic-bezier(0.32,0.72,0,1)"
			}
	},
	beforeHPx: {
			"::before": {
					content: "\"\"",
					height: "1px"
			}
	},
	beforeInset0: {
			"::before": {
					content: "\"\"",
					inset: "0"
			}
	},
	beforeInset05: {
			"::before": {
					content: "\"\"",
					inset: "calc(4px * 0.5)"
			}
	},
	beforeInset2: {
			"::before": {
					content: "\"\"",
					inset: "calc(4px * 2)"
			}
	},
	beforeInset3px: {
			"::before": {
					content: "\"\"",
					inset: "3px"
			}
	},
	beforeLeft12: {
			"::before": {
					content: "\"\"",
					left: "calc(1 / 2 * 100%)"
			}
	},
	beforeOpacity0: {
			"::before": {
					content: "\"\"",
					opacity: "0%"
			}
	},
	beforeOpacity100: {
			"::before": {
					content: "\"\"",
					opacity: "100%"
			}
	},
	beforePointerEventsNone: {
			"::before": {
					content: "\"\"",
					pointerEvents: "none"
			}
	},
	beforeRoundedCalc6pxVarRf: {
			"::before": {
					content: "\"\"",
					borderRadius: "calc(6px * var(--rf))",
					cornerShape: "var(--cs)"
			}
	},
	beforeRoundedCalc9pxVarRf: {
			"::before": {
					content: "\"\"",
					borderRadius: "calc(9px * var(--rf))",
					cornerShape: "var(--cs)"
			}
	},
	beforeRoundedInherit: {
			"::before": {
					content: "\"\"",
					borderRadius: "inherit",
					cornerShape: "var(--cs)"
			}
	},
	beforeRoundedMd: {
			"::before": {
					content: "\"\"",
					borderRadius: "calc(7px * var(--rf))",
					cornerShape: "var(--cs)"
			}
	},
	beforeRoundedSm: {
			"::before": {
					content: "\"\"",
					borderRadius: "calc(4px * var(--rf))",
					cornerShape: "var(--cs)"
			}
	},
	beforeSize7: {
			"::before": {
					content: "\"\"",
					width: "calc(4px * 7)",
					height: "calc(4px * 7)"
			}
	},
	beforeTextMeta: {
			"::before": {
					content: "\"\"",
					fontSize: "var(--type-meta)",
					fontWeight: "var(--tw-font-weight, var(--font-weight-normal))"
			}
	},
	beforeTop12: {
			"::before": {
					content: "\"\"",
					top: "calc(1 / 2 * 100%)"
			}
	},
	beforeTransitionBackground: {
			"::before": {
					content: "\"\"",
					transitionProperty: "background",
					transitionTimingFunction: "var(--tw-ease, var(--ease))",
					transitionDuration: "var(--tw-duration, var(--dur-micro))"
			}
	},
	beforeTransitionColors: {
			"::before": {
					content: "\"\"",
					transitionProperty: "color, background-color, border-color, outline-color, text-decoration-color, fill, stroke, --tw-gradient-from, --tw-gradient-via, --tw-gradient-to",
					transitionTimingFunction: "var(--tw-ease, var(--ease))",
					transitionDuration: "var(--tw-duration, var(--dur-micro))"
			}
	},
	beforeTransitionOpacity: {
			"::before": {
					content: "\"\"",
					transitionProperty: "opacity",
					transitionTimingFunction: "var(--tw-ease, var(--ease))",
					transitionDuration: "var(--tw-duration, var(--dur-micro))"
			}
	},
	beforeZ0: {
			"::before": {
					content: "\"\"",
					zIndex: "0"
			}
	},
	bgColorMixInSrgbVarAccent12Transparent: {
			backgroundColor: "color-mix(in srgb,var(--accent) 12%,transparent)"
	},
	bgColorMixInSrgbVarAccent16Transparent: {
			backgroundColor: "color-mix(in srgb,var(--accent) 16%,transparent)"
	},
	bgColorMixInSrgbVarBg72Transparent: {
			backgroundColor: "color-mix(in srgb,var(--bg) 72%,transparent)"
	},
	bgColorMixInSrgbVarBg92Transparent: {
			backgroundColor: "color-mix(in srgb,var(--bg) 92%,transparent)"
	},
	bgColorMixInSrgbVarBgPanel68Transparent: {
			backgroundColor: "color-mix(in srgb,var(--bg-panel) 68%,transparent)"
	},
	bgColorMixInSrgbVarBgPanel80VarComposerSurface: {
			backgroundColor: "color-mix(in srgb,var(--bg-panel) 80%,var(--composer-surface))"
	},
	bgColorMixInSrgbVarYellow16Transparent: {
			backgroundColor: "color-mix(in srgb,var(--yellow) 16%,transparent)"
	},
	bgVarBgHover: {
			backgroundColor: "var(--bg-hover)"
	},
	bgVarComposerSurface: {
			backgroundColor: "var(--composer-surface)"
	},
	bgAccent: {
			backgroundColor: "var(--accent)"
	},
	bgAccentSoft: {
			backgroundColor: "var(--accent-soft)"
	},
	bgActive: {
			backgroundColor: "var(--bg-active)"
	},
	bgBg: {
			backgroundColor: "var(--bg)"
	},
	bgBg65: {
			backgroundColor: "color-mix(in oklab, var(--bg) 65%, transparent)"
	},
	bgBg85: {
			backgroundColor: "color-mix(in oklab, var(--bg) 85%, transparent)"
	},
	bgBlack45: {
			backgroundColor: "color-mix(in oklab, var(--color-black) 45%, transparent)"
	},
	bgBlack50: {
			backgroundColor: "color-mix(in oklab, var(--color-black) 50%, transparent)"
	},
	bgBlue: {
			backgroundColor: "var(--blue)"
	},
	bgBlueSoft: {
			backgroundColor: "var(--blue-soft)"
	},
	bgClipText: {
			backgroundClip: "text"
	},
	bgDim35: {
			backgroundColor: "color-mix(in oklab, var(--text-dim) 35%, transparent)"
	},
	bgDivider: {
			backgroundColor: "var(--divider)"
	},
	bgFaint: {
			backgroundColor: "var(--text-faint)"
	},
	bgFaint10: {
			backgroundColor: "color-mix(in oklab, var(--text-faint) 10%, transparent)"
	},
	bgFaint35: {
			backgroundColor: "color-mix(in oklab, var(--text-faint) 35%, transparent)"
	},
	bgFg: {
			backgroundColor: "var(--text)"
	},
	bgFg15: {
			backgroundColor: "color-mix(in oklab, var(--text) 15%, transparent)"
	},
	bgFg45: {
			backgroundColor: "color-mix(in oklab, var(--text) 45%, transparent)"
	},
	bgGreen: {
			backgroundColor: "var(--green)"
	},
	bgGreenSoft: {
			backgroundColor: "var(--green-soft)"
	},
	bgHover: {
			backgroundColor: "var(--hover)"
	},
	bgHover50: {
			backgroundColor: "color-mix(in oklab, var(--hover) 50%, transparent)"
	},
	bgLine: {
			backgroundColor: "var(--border)"
	},
	bgPaletteGlass: {
			backgroundColor: "var(--palette-glass)"
	},
	bgPanel: {
			backgroundColor: "var(--bg-panel)"
	},
	bgPopup: {
			backgroundColor: "var(--popup-surface)"
	},
	bgPopupGlass: {
			backgroundColor: "var(--popup-glass)"
	},
	bgPressed: {
			backgroundColor: "var(--hover-strong)"
	},
	bgRaised: {
			backgroundColor: "var(--bg-raised)"
	},
	bgRed: {
			backgroundColor: "var(--red)"
	},
	bgRedSoft: {
			backgroundColor: "var(--red-soft)"
	},
	bgSelected: {
			backgroundColor: "var(--selected)"
	},
	bgSettingsPlate: {
			backgroundColor: "var(--settings-plate)"
	},
	bgSidebar: {
			backgroundColor: "var(--sidebar-bg)"
	},
	bgSurface: {
			backgroundColor: "var(--bg)"
	},
	bgTransparent: {
			backgroundColor: "transparent"
	},
	bgYellow: {
			backgroundColor: "var(--yellow)"
	},
	block: {
			display: "block"
	},
	border: {
			borderStyle: "solid",
			borderWidth: "1px"
	},
	border0: {
			borderStyle: "solid",
			borderWidth: "0px"
	},
	borderColorMixInSrgbVarAccent40Transparent: {
			borderColor: "color-mix(in srgb,var(--accent) 40%,transparent)"
	},
	borderColorColorMixInSrgbVarComposerBorder35Transparent: {
			borderColor: "color-mix(in srgb,var(--composer-border) 35%,transparent)"
	},
	borderColorVarComposerBorder: {
			borderColor: "var(--composer-border)"
	},
	borderColorVarMobileHeaderControlBorder: {
			borderColor: "var(--mobile-header-control-border)"
	},
	borderRgba1314813605: {
			borderColor: "rgba(13,148,136,0.5)"
	},
	borderRgba9410621005: {
			borderColor: "rgba(94,106,210,0.5)"
	},
	borderVarAccent6b8afd: {
			borderColor: "var(--accent,#6b8afd)"
	},
	borderAccent: {
			borderColor: "var(--accent)"
	},
	borderB: {
			borderBottomStyle: "solid",
			borderBottomWidth: "1px"
	},
	borderBg: {
			borderColor: "var(--bg)"
	},
	borderCurrent25: {
			borderColor: "color-mix(in oklab, currentcolor 25%, transparent)"
	},
	borderDivider: {
			borderColor: "var(--divider)"
	},
	borderDividerSoft: {
			borderColor: "var(--divider-soft)"
	},
	borderL: {
			borderLeftStyle: "solid",
			borderLeftWidth: "1px"
	},
	borderLine: {
			borderColor: "var(--border)"
	},
	borderLineStrong: {
			borderColor: "var(--border-strong)"
	},
	borderNone: {
			borderStyle: "none"
	},
	borderR: {
			borderRightStyle: "solid",
			borderRightWidth: "1px"
	},
	borderT: {
			borderTopStyle: "solid",
			borderTopWidth: "1px"
	},
	borderTCurrent: {
			borderTopColor: "currentcolor"
	},
	borderTransparent: {
			borderColor: "transparent"
	},
	borderX: {
			borderInlineStyle: "solid",
			borderInlineWidth: "1px"
	},
	bottom0: {
			bottom: "0"
	},
	bottom2: {
			bottom: "calc(4px * 2)"
	},
	bottom124px: {
			bottom: "124px"
	},
	bottom72px: {
			bottom: "72px"
	},
	bottomCalc1006px: {
			bottom: "calc(100% + 6px)"
	},
	bottomCalc24pxVarSuggestionsUnder0px: {
			bottom: "calc(24px + var(--suggestions-under,0px))"
	},
	bottomMax12pxEnvSafeAreaInsetBottom0px: {
			bottom: "max(12px, env(safe-area-inset-bottom,0px))"
	},
	bottomFull: {
			bottom: "100%"
	},
	breakAll: {
			wordBreak: "break-all"
	},
	breakWords: {
			overflowWrap: "break-word"
	},
	caretVarText: {
			caretColor: "var(--text)"
	},
	contents: {
			display: "contents"
	},
	cursorColResize: {
			cursor: "col-resize"
	},
	cursorDefault: {
			cursor: "default"
	},
	cursorGrab: {
			cursor: "grab"
	},
	cursorPointer: {
			cursor: "pointer"
	},
	cursorText: {
			cursor: "text"
	},
	desktopMt11px: {
			"@media (min-width: 721px)": {
					marginTop: "calc(11px * -1)"
			}
	},
	desktopBorderTransparent: {
			"@media (min-width: 721px)": {
					borderColor: "transparent"
			}
	},
	desktopColSpan2: {
			"@media (min-width: 721px)": {
					gridColumn: "span 2 / span 2"
			}
	},
	desktopColStart1: {
			"@media (min-width: 721px)": {
					gridColumnStart: "1"
			}
	},
	desktopColStart2: {
			"@media (min-width: 721px)": {
					gridColumnStart: "2"
			}
	},
	desktopContents: {
			"@media (min-width: 721px)": {
					display: "contents"
			}
	},
	desktopFlex: {
			"@media (min-width: 721px)": {
					display: "flex"
			}
	},
	desktopGap10: {
			"@media (min-width: 721px)": {
					gap: "calc(4px * 10)"
			}
	},
	desktopGap9px: {
			"@media (min-width: 721px)": {
					gap: "9px"
			}
	},
	desktopGrid: {
			"@media (min-width: 721px)": {
					display: "grid"
			}
	},
	desktopGridCols3: {
			"@media (min-width: 721px)": {
					gridTemplateColumns: "repeat(3, minmax(0, 1fr))"
			}
	},
	desktopGridCols4: {
			"@media (min-width: 721px)": {
					gridTemplateColumns: "repeat(4, minmax(0, 1fr))"
			}
	},
	desktopGridCols3fr2fr: {
			"@media (min-width: 721px)": {
					gridTemplateColumns: "3fr 2fr"
			}
	},
	desktopGridColsMinmax01fr13rem: {
			"@media (min-width: 721px)": {
					gridTemplateColumns: "minmax(0,1fr) 13rem"
			}
	},
	desktopGridColsMinmax01frAutoMinmax01fr: {
			"@media (min-width: 721px)": {
					gridTemplateColumns: "minmax(0,1fr) auto minmax(0,1fr)"
			}
	},
	desktopGridColsMinmax0720px220px: {
			"@media (min-width: 721px)": {
					gridTemplateColumns: "minmax(0,720px) 220px"
			}
	},
	desktopGridColsRepeatAutoFit200px: {
			"@media (min-width: 721px)": {
					gridTemplateColumns: "repeat(auto-fit,200px)"
			}
	},
	desktopH22rem: {
			"@media (min-width: 721px)": {
					height: "22rem"
			}
	},
	desktopHVarSidebarBandSlot: {
			"@media (min-width: 721px)": {
					height: "var(--sidebar-band-slot)"
			}
	},
	desktopHVarSidebarCapH: {
			"@media (min-width: 721px)": {
					height: "var(--sidebar-cap-h)"
			}
	},
	desktopHVarSidebarLineH: {
			"@media (min-width: 721px)": {
					height: "var(--sidebar-line-h)"
			}
	},
	desktopHFull: {
			"@media (min-width: 721px)": {
					height: "100%"
			}
	},
	desktopHidden: {
			"@media (min-width: 721px)": {
					display: "none"
			}
	},
	desktopInlineFlex: {
			"@media (min-width: 721px)": {
					display: "inline-flex"
			}
	},
	desktopItemsCenter: {
			"@media (min-width: 721px)": {
					alignItems: "center"
			}
	},
	desktopMinH0: {
			"@media (min-width: 721px)": {
					minHeight: "0"
			}
	},
	desktopMinH60: {
			"@media (min-width: 721px)": {
					minHeight: "calc(4px * 60)"
			}
	},
	desktopMinHVarSidebarBandSlot: {
			"@media (min-width: 721px)": {
					minHeight: "var(--sidebar-band-slot)"
			}
	},
	desktopMinHVarSidebarCapH: {
			"@media (min-width: 721px)": {
					minHeight: "var(--sidebar-cap-h)"
			}
	},
	desktopMinHVarSidebarLineH: {
			"@media (min-width: 721px)": {
					minHeight: "var(--sidebar-line-h)"
			}
	},
	desktopMinW34px: {
			"@media (min-width: 721px)": {
					minWidth: "34px"
			}
	},
	desktopMl0: {
			"@media (min-width: 721px)": {
					marginLeft: "0"
			}
	},
	desktopMr35: {
			"@media (min-width: 721px)": {
					marginRight: "calc(4px * 3.5)"
			}
	},
	desktopMr312px: {
			"@media (min-width: 721px)": {
					marginRight: "312px"
			}
	},
	desktopMr320px: {
			"@media (min-width: 721px)": {
					marginRight: "320px"
			}
	},
	desktopMt0: {
			"@media (min-width: 721px)": {
					marginTop: "0"
			}
	},
	desktopMxVarSidebarNavX: {
			"@media (min-width: 721px)": {
					marginInline: "var(--sidebar-nav-x)"
			}
	},
	desktopPb1: {
			"@media (min-width: 721px)": {
					paddingBottom: "4px"
			}
	},
	desktopPb5: {
			"@media (min-width: 721px)": {
					paddingBottom: "calc(4px * 5)"
			}
	},
	desktopPl0: {
			"@media (min-width: 721px)": {
					paddingLeft: "0"
			}
	},
	desktopPlCalcVarSidebarIconLeft16pxVarSidebarNavX6px: {
			"@media (min-width: 721px)": {
					paddingLeft: "calc(var(--sidebar-icon-left,16px) - var(--sidebar-nav-x,6px))"
			}
	},
	desktopPr0: {
			"@media (min-width: 721px)": {
					paddingRight: "0"
			}
	},
	desktopPr1: {
			"@media (min-width: 721px)": {
					paddingRight: "4px"
			}
	},
	desktopPr7: {
			"@media (min-width: 721px)": {
					paddingRight: "calc(4px * 7)"
			}
	},
	desktopPt05: {
			"@media (min-width: 721px)": {
					paddingTop: "calc(4px * 0.5)"
			}
	},
	desktopPt1: {
			"@media (min-width: 721px)": {
					paddingTop: "4px"
			}
	},
	desktopPt3: {
			"@media (min-width: 721px)": {
					paddingTop: "calc(4px * 3)"
			}
	},
	desktopPx5: {
			"@media (min-width: 721px)": {
					paddingInline: "calc(4px * 5)"
			}
	},
	desktopPxVarSidebarNavX: {
			"@media (min-width: 721px)": {
					paddingInline: "var(--sidebar-nav-x)"
			}
	},
	desktopPy0: {
			"@media (min-width: 721px)": {
					paddingBlock: "0"
			}
	},
	desktopRowStart1: {
			"@media (min-width: 721px)": {
					gridRowStart: "1"
			}
	},
	desktopRowStart2: {
			"@media (min-width: 721px)": {
					gridRowStart: "2"
			}
	},
	desktopRowStart3: {
			"@media (min-width: 721px)": {
					gridRowStart: "3"
			}
	},
	desktopSize200px: {
			"@media (min-width: 721px)": {
					width: "200px",
					height: "200px"
			}
	},
	desktopSmoothShadowRingSoft: {
			"@media (min-width: 721px)": {
					boxShadow: "0 3px 10px -3px\tcolor-mix(in srgb, var(--smooth-shadow-color) 4%, transparent),\t0 20px 56px -16px\tcolor-mix(in srgb, var(--smooth-shadow-color) 12%, transparent),\t0 0 0 var(--smooth-ring-width, 1px)\tcolor-mix(in srgb, var(--smooth-ring-color) 35%, transparent)"
			}
	},
	desktopSticky: {
			"@media (min-width: 721px)": {
					position: "sticky"
			}
	},
	desktopTextItemTitle: {
			"@media (min-width: 721px)": {
					fontSize: "var(--type-item-title)"
			}
	},
	desktopTop0: {
			"@media (min-width: 721px)": {
					top: "0"
			}
	},
	desktopTopCalcVarSidebarBandSlotVarSidebarLineH: {
			"@media (min-width: 721px)": {
					top: "calc(var(--sidebar-band-slot) + var(--sidebar-line-h))"
			}
	},
	desktopTopVarSidebarBandSlot: {
			"@media (min-width: 721px)": {
					top: "var(--sidebar-band-slot)"
			}
	},
	desktopWFull: {
			"@media (min-width: 721px)": {
					width: "100%"
			}
	},
	desktopZ20: {
			"@media (min-width: 721px)": {
					zIndex: "20"
			}
	},
	desktopZ14: {
			"@media (min-width: 721px)": {
					zIndex: "14"
			}
	},
	desktopZ15: {
			"@media (min-width: 721px)": {
					zIndex: "15"
			}
	},
	disabledCursorDefault: {
			":disabled": {
					cursor: "default"
			}
	},
	disabledOpacity100: {
			":disabled": {
					opacity: "100%"
			}
	},
	disabledOpacity35: {
			":disabled": {
					opacity: "35%"
			}
	},
	disabledOpacity70: {
			":disabled": {
					opacity: "70%"
			}
	},
	disabledPointerEventsNone: {
			":disabled": {
					pointerEvents: "none"
			}
	},
	durationDur: {
			transitionDuration: "var(--dur)"
	},
	durationDurMicro: {
			transitionDuration: "var(--dur-micro)"
	},
	duration150: {
			transitionDuration: "150ms"
	},
	duration300: {
			transitionDuration: "300ms"
	},
	durationVarDur: {
			transitionDuration: "var(--dur)"
	},
	durationVarDurLg: {
			transitionDuration: "var(--dur-lg)"
	},
	durationVarDurMicro: {
			transitionDuration: "var(--dur-micro)"
	},
	easeEase: {
			transitionTimingFunction: "var(--ease)"
	},
	easeVarEase: {
			transitionTimingFunction: "var(--ease)"
	},
	fixed: {
			position: "fixed"
	},
	flex: {
			display: "flex"
	},
	flex1: {
			flex: "1"
	},
	flex0022px: {
			flex: "0 0 22px"
	},
	flex00340px: {
			flex: "0 0 340px"
	},
	flex00Auto: {
			flex: "0 0 auto"
	},
	flex01Auto: {
			flex: "0 1 auto"
	},
	flexAuto: {
			flex: "auto"
	},
	flexCol: {
			flexDirection: "column"
	},
	flexNone: {
			flex: "none"
	},
	flexShrink0: {
			flexShrink: "0"
	},
	flexWrap: {
			flexWrap: "wrap"
	},
	focusVisibleAfterBorderLineStrong: {
			"::after": {
					content: "\"\"",
					borderColor: "var(--border-strong)"
			}
	},
	focusVisibleOpacity100: {
			":focus-visible": {
					opacity: "100%"
			}
	},
	focusVisibleOutlineFg: {
			":focus-visible": {
					outlineColor: "var(--text)"
			}
	},
	focusVisibleOutlineOffset2: {
			":focus-visible": {
					outlineOffset: "2px"
			}
	},
	focusVisibleRingVarAccent6b8afd: {
			":focus-visible": {}
	},
	focusVisibleRingAccent50: {
			":focus-visible": {}
	},
	focusVisibleRingInset: {
			":focus-visible": {}
	},
	focusBorderTransparent: {
			":focus": {
					borderColor: "transparent"
			}
	},
	fontInherit: {
			fontFamily: "inherit"
	},
	fontBold: {
			fontWeight: "var(--font-weight-bold)"
	},
	fontMedium: {
			fontWeight: "var(--font-weight-medium)"
	},
	fontMono: {
			fontFamily: "var(--mono)"
	},
	fontSemibold: {
			fontWeight: "var(--font-weight-semibold)"
	},
	gap0: {
			gap: "0"
	},
	gap05: {
			gap: "calc(4px * 0.5)"
	},
	gap1: {
			gap: "4px"
	},
	gap15: {
			gap: "calc(4px * 1.5)"
	},
	gap2: {
			gap: "calc(4px * 2)"
	},
	gap25: {
			gap: "calc(4px * 2.5)"
	},
	gap3: {
			gap: "calc(4px * 3)"
	},
	gap35: {
			gap: "calc(4px * 3.5)"
	},
	gap4: {
			gap: "calc(4px * 4)"
	},
	gap5px: {
			gap: "5px"
	},
	gap7px: {
			gap: "7px"
	},
	gap9px: {
			gap: "9px"
	},
	gapPx: {
			gap: "1px"
	},
	gapX1: {
			columnGap: "4px"
	},
	gapX2: {
			columnGap: "calc(4px * 2)"
	},
	gapX3: {
			columnGap: "calc(4px * 3)"
	},
	gapX4: {
			columnGap: "calc(4px * 4)"
	},
	gapY1: {
			rowGap: "4px"
	},
	gapY15: {
			rowGap: "calc(4px * 1.5)"
	},
	gapY25: {
			rowGap: "calc(4px * 2.5)"
	},
	grid: {
			display: "grid"
	},
	gridCols1: {
			gridTemplateColumns: "repeat(1, minmax(0, 1fr))"
	},
	gridCols2: {
			gridTemplateColumns: "repeat(2, minmax(0, 1fr))"
	},
	gridCols6: {
			gridTemplateColumns: "repeat(6, minmax(0, 1fr))"
	},
	gridCols24pxMinmax01fr: {
			gridTemplateColumns: "24px minmax(0,1fr)"
	},
	gridColsMinmax01fr575rem: {
			gridTemplateColumns: "minmax(0,1fr) 5.75rem"
	},
	gridColsMinmax01frAuto: {
			gridTemplateColumns: "minmax(0,1fr) auto"
	},
	gridColsMinmax0300pxMinmax01fr: {
			gridTemplateColumns: "minmax(0,300px) minmax(0,1fr)"
	},
	gridRows44pxMinmax01fr: {
			gridTemplateRows: "44px minmax(0,1fr)"
	},
	h11: {
			height: "calc(4px * 11)"
	},
	h12: {
			height: "calc(4px * 12)"
	},
	h122: {
			height: "calc(4px * 12) !important"
	},
	h2: {
			height: "calc(4px * 2)"
	},
	h25: {
			height: "calc(4px * 2.5)"
	},
	h4: {
			height: "calc(4px * 4)"
	},
	h7: {
			height: "calc(4px * 7)"
	},
	h8: {
			height: "calc(4px * 8)"
	},
	h100dvh: {
			height: "100dvh"
	},
	h18px: {
			height: "18px"
	},
	h22px: {
			height: "22px"
	},
	h31px: {
			height: "31px"
	},
	h34px: {
			height: "34px"
	},
	h52px: {
			height: "52px"
	},
	h94dvh: {
			height: "94dvh"
	},
	hMin500px76vh: {
			height: "min(500px, 76vh)"
	},
	hMin820px85vh: {
			height: "min(820px, 85vh)"
	},
	hMin840pxCalc100dvh32px: {
			height: "min(840px, calc(100dvh - 32px))"
	},
	hVarDesktopHeaderH: {
			height: "var(--desktop-header-h)"
	},
	hFull: {
			height: "100%"
	},
	hidden: {
			display: "none"
	},
	hoverAfterBgLineStrong: {
			"@media (hover: hover)": {
					"::after": {
							content: "\"\"",
							backgroundColor: "var(--border-strong)"
					}
			}
	},
	hoverAfterBorderLineStrong: {
			"@media (hover: hover)": {
					"::after": {
							content: "\"\"",
							borderColor: "var(--border-strong)"
					}
			}
	},
	hoverBeforeBgHover: {
			"@media (hover: hover)": {
					"::before": {
							content: "\"\"",
							backgroundColor: "var(--hover)"
					}
			}
	},
	hoverBeforeBgPressed: {
			"@media (hover: hover)": {
					"::before": {
							content: "\"\"",
							backgroundColor: "var(--hover-strong)"
					}
			}
	},
	hoverBgImageLinearGradientVarHoverVarHover: {
			"@media (hover: hover)": {
					":hover": {
							backgroundImage: "linear-gradient(var(--hover),var(--hover))"
					}
			}
	},
	hoverBgVarRowChip: {
			"@media (hover: hover)": {
					":hover": {
							backgroundColor: "var(--row-chip)"
					}
			}
	},
	hoverBgFg85: {
			"@media (hover: hover)": {
					":hover": {
							backgroundColor: "color-mix(in oklab, var(--text) 85%, transparent)"
					}
			}
	},
	hoverBgHover: {
			"@media (hover: hover)": {
					":hover": {
							backgroundColor: "var(--hover)"
					}
			}
	},
	hoverBgHover40: {
			"@media (hover: hover)": {
					":hover": {
							backgroundColor: "color-mix(in oklab, var(--hover) 40%, transparent)"
					}
			}
	},
	hoverBgPanel: {
			"@media (hover: hover)": {
					":hover": {
							backgroundColor: "var(--bg-panel)"
					}
			}
	},
	hoverBorderLineStrong: {
			"@media (hover: hover)": {
					":hover": {
							borderColor: "var(--border-strong)"
					}
			}
	},
	hoverBorderTransparent: {
			"@media (hover: hover)": {
					":hover": {
							borderColor: "transparent"
					}
			}
	},
	hoverPr68px: {
			"@media (hover: hover)": {
					":hover": {
							paddingRight: "68px"
					}
			}
	},
	hoverScale110: {
			"@media (hover: hover)": {
					":hover": {
							scale: "110% 110%"
					}
			}
	},
	hoverTextDim: {
			"@media (hover: hover)": {
					":hover": {
							color: "var(--text-dim)"
					}
			}
	},
	hoverTextFg: {
			"@media (hover: hover)": {
					":hover": {
							color: "var(--text)"
					}
			}
	},
	hoverTextGreen: {
			"@media (hover: hover)": {
					":hover": {
							color: "var(--green)"
					}
			}
	},
	hoverTextRed: {
			"@media (hover: hover)": {
					":hover": {
							color: "var(--red)"
					}
			}
	},
	hoverUnderline: {
			"@media (hover: hover)": {
					":hover": {
							textDecorationLine: "underline"
					}
			}
	},
	inlineFlex: {
			display: "inline-flex"
	},
	inset0: {
			inset: "0"
	},
	insetX0: {
			insetInline: "0"
	},
	invisible: {
			visibility: "hidden"
	},
	isolate: {
			isolation: "isolate"
	},
	itemsCenter: {
			alignItems: "center"
	},
	itemsStart: {
			alignItems: "flex-start"
	},
	itemsStretch: {
			alignItems: "stretch"
	},
	justifyBetween: {
			justifyContent: "space-between"
	},
	justifyCenter: {
			justifyContent: "center"
	},
	justifyEnd: {
			justifyContent: "flex-end"
	},
	justifySelfCenter: {
			justifySelf: "center"
	},
	justifyStart: {
			justifyContent: "flex-start"
	},
	leading4: {
			lineHeight: "calc(4px * 4)"
	},
	leading12: {
			lineHeight: "1.2"
	},
	leading145: {
			lineHeight: "1.45"
	},
	leading155: {
			lineHeight: "1.55"
	},
	leading52px: {
			lineHeight: "52px"
	},
	leadingNone: {
			lineHeight: "1"
	},
	left0: {
			left: "0"
	},
	left12: {
			left: "calc(1 / 2 * 100%)"
	},
	left14: {
			left: "calc(4px * 14)"
	},
	left2: {
			left: "calc(4px * 2)"
	},
	left3: {
			left: "calc(4px * 3)"
	},
	leftCalc1VarComposerInsetLeft17px: {
			left: "calc(-1 * var(--composer-inset-left,17px))"
	},
	lineClamp4: {
			overflow: "hidden",
			display: "-webkit-box",
			WebkitBoxOrient: "vertical",
			WebkitLineClamp: "4"
	},
	m0: {
			margin: "0"
	},
	max560pxHMin560px82vh: {
			"@media (max-width: 559px)": {
					height: "min(560px, 82vh)"
			}
	},
	max560pxHidden: {
			"@media (max-width: 559px)": {
					display: "none"
			}
	},
	max560pxMb4: {
			"@media (max-width: 559px)": {
					marginBottom: "calc(4px * 4)"
			}
	},
	max560pxPb12: {
			"@media (max-width: 559px)": {
					paddingBottom: "calc(4px * 12)"
			}
	},
	max560pxPt18px: {
			"@media (max-width: 559px)": {
					paddingTop: "18px"
			}
	},
	max560pxPx4: {
			"@media (max-width: 559px)": {
					paddingInline: "calc(4px * 4)"
			}
	},
	max900pxBorderL0: {
			"@media (max-width: 899px)": {
					borderLeftStyle: "solid",
					borderLeftWidth: "0px"
			}
	},
	max900pxHidden: {
			"@media (max-width: 899px)": {
					display: "none"
			}
	},
	max900pxInlineFlex: {
			"@media (max-width: 899px)": {
					display: "inline-flex"
			}
	},
	maxH320px: {
			maxHeight: "320px"
	},
	maxHCalc100dvh32px: {
			maxHeight: "calc(100dvh - 32px)"
	},
	maxHMin72vh640px: {
			maxHeight: "min(72vh, 640px)"
	},
	maxHFull: {
			maxHeight: "100%"
	},
	maxHNone: {
			maxHeight: "none"
	},
	maxSmGridCols1: {
			"@media (max-width: 39.999rem)": {
					gridTemplateColumns: "repeat(1, minmax(0, 1fr))"
			}
	},
	maxSmMinH10: {
			"@media (max-width: 39.999rem)": {
					minHeight: "calc(4px * 10)"
			}
	},
	maxSmMinW55: {
			"@media (max-width: 39.999rem)": {
					minWidth: "55%"
			}
	},
	maxW1040px: {
			maxWidth: "1040px"
	},
	maxW1160px: {
			maxWidth: "1160px"
	},
	maxW240px: {
			maxWidth: "240px"
	},
	maxW25rem: {
			maxWidth: "25rem"
	},
	maxW280px: {
			maxWidth: "280px"
	},
	maxW30rem: {
			maxWidth: "30rem"
	},
	maxW31rem: {
			maxWidth: "31rem"
	},
	maxW32rem: {
			maxWidth: "32rem"
	},
	maxW34rem: {
			maxWidth: "34rem"
	},
	maxW40rem: {
			maxWidth: "40rem"
	},
	maxW420px: {
			maxWidth: "420px"
	},
	maxW48rem: {
			maxWidth: "48rem"
	},
	maxW720px: {
			maxWidth: "720px"
	},
	maxW750px: {
			maxWidth: "750px"
	},
	maxW780px: {
			maxWidth: "780px"
	},
	maxW880px: {
			maxWidth: "880px"
	},
	maxWCalc100vw16px: {
			maxWidth: "calc(100vw - 16px)"
	},
	maxWCalcVarSessionCol40px: {
			maxWidth: "calc(var(--session-col) + 40px)"
	},
	maxWMin320pxCalc100vw1rem: {
			maxWidth: "min(320px, calc(100vw - 1rem))"
	},
	maxWMin360pxCalc100vw1rem: {
			maxWidth: "min(360px, calc(100vw - 1rem))"
	},
	maxWFull: {
			maxWidth: "100%"
	},
	maxWNone: {
			maxWidth: "none"
	},
	mb05: {
			marginBottom: "calc(4px * 0.5)"
	},
	mb1: {
			marginBottom: "4px"
	},
	mb2: {
			marginBottom: "calc(4px * 2)"
	},
	mb3: {
			marginBottom: "calc(4px * 3)"
	},
	mb4: {
			marginBottom: "calc(4px * 4)"
	},
	mb5: {
			marginBottom: "calc(4px * 5)"
	},
	mbVarSidebarGroupGap: {
			marginBottom: "var(--sidebar-group-gap)"
	},
	mdMl4: {
			"@media (min-width: 48rem)": {
					marginLeft: "calc(4px * 4)"
			}
	},
	mdMr2: {
			"@media (min-width: 48rem)": {
					marginRight: "calc(4px * 2)"
			}
	},
	mdOpacity0: {
			"@media (min-width: 48rem)": {
					opacity: "0%"
			}
	},
	minH0: {
			minHeight: "0"
	},
	minH10: {
			minHeight: "calc(4px * 10)"
	},
	minH11: {
			minHeight: "calc(4px * 11)"
	},
	minH12: {
			minHeight: "calc(4px * 12) !important"
	},
	minH20: {
			minHeight: "calc(4px * 20)"
	},
	minH28: {
			minHeight: "calc(4px * 28)"
	},
	minH6: {
			minHeight: "calc(4px * 6)"
	},
	minH8: {
			minHeight: "calc(4px * 8)"
	},
	minH320px: {
			minHeight: "320px"
	},
	minH38px: {
			minHeight: "38px"
	},
	minHCalc13px145: {
			minHeight: "calc(13px * 1.45)"
	},
	minHCalcEnvSafeAreaInsetTop0px52px: {
			minHeight: "calc(env(safe-area-inset-top,0px) + 52px)"
	},
	minHVarSidebarCapH: {
			minHeight: "var(--sidebar-cap-h)"
	},
	minW0: {
			minWidth: "0"
	},
	minW4: {
			minWidth: "calc(4px * 4)"
	},
	minW172px: {
			minWidth: "172px"
	},
	minW18px: {
			minWidth: "18px"
	},
	minW220px: {
			minWidth: "220px"
	},
	minW28px: {
			minWidth: "28px"
	},
	minW34px: {
			minWidth: "34px"
	},
	ml0: {
			marginLeft: "0"
	},
	ml15: {
			marginLeft: "calc(4px * 1.5)"
	},
	ml4: {
			marginLeft: "calc(4px * 4)"
	},
	ml5px: {
			marginLeft: "5px"
	},
	mlAuto: {
			marginLeft: "auto"
	},
	motionReduceAnimationDuration12s: {
			"@media (prefers-reduced-motion: reduce)": {
					"@media (prefers-reduced-motion:reduce)": {
							animationDuration: "1.2s !important"
					}
			}
	},
	motionReduceAnimationDuration14s: {
			"@media (prefers-reduced-motion: reduce)": {
					"@media (prefers-reduced-motion:reduce)": {
							animationDuration: "1.4s !important"
					}
			}
	},
	motionReduceAnimationIterationCountInfinite: {
			"@media (prefers-reduced-motion: reduce)": {
					"@media (prefers-reduced-motion:reduce)": {
							animationIterationCount: "infinite !important"
					}
			}
	},
	motionReduceAnimateNone: {
			"@media (prefers-reduced-motion: reduce)": {
					"@media (prefers-reduced-motion:reduce)": {
							animation: "none"
					}
			}
	},
	motionReduceTransformNone: {
			"@media (prefers-reduced-motion: reduce)": {
					"@media (prefers-reduced-motion:reduce)": {
							transform: "none"
					}
			}
	},
	motionReduceTransitionNone: {
			"@media (prefers-reduced-motion: reduce)": {
					"@media (prefers-reduced-motion:reduce)": {
							transitionProperty: "none"
					}
			}
	},
	motionSafeAnimatePulse: {
			"@media (prefers-reduced-motion: no-preference)": {
					animation: "var(--animate-pulse)"
			}
	},
	motionSafeDuration150: {
			"@media (prefers-reduced-motion: no-preference)": {
					transitionDuration: "150ms"
			}
	},
	motionSafeTransitionOpacity: {
			"@media (prefers-reduced-motion: no-preference)": {
					transitionProperty: "opacity",
					transitionTimingFunction: "var(--tw-ease, var(--ease))",
					transitionDuration: "var(--tw-duration, var(--dur-micro))"
			}
	},
	mr15: {
			marginRight: "calc(4px * 1.5)"
	},
	mt0: {
			marginTop: "0"
	},
	mt05: {
			marginTop: "calc(4px * 0.5)"
	},
	mt1: {
			marginTop: "4px"
	},
	mt2: {
			marginTop: "calc(4px * 2)"
	},
	mt25: {
			marginTop: "calc(4px * 2.5)"
	},
	mt3: {
			marginTop: "calc(4px * 3)"
	},
	mt4: {
			marginTop: "calc(4px * 4)"
	},
	mt9: {
			marginTop: "calc(4px * 9)"
	},
	mt9px: {
			marginTop: "9px"
	},
	mtCalc1VarSessionUnder: {
			marginTop: "calc(-1 * var(--session-under))"
	},
	mx15: {
			marginInline: "calc(4px * 1.5)"
	},
	mx2: {
			marginInline: "calc(4px * 2)"
	},
	mx3: {
			marginInline: "calc(4px * 3)"
	},
	mx35: {
			marginInline: "calc(4px * 3.5)"
	},
	mxAuto: {
			marginInline: "auto"
	},
	my2px: {
			marginBlock: "-2px"
	},
	noUnderline: {
			textDecorationLine: "none"
	},
	objectCover: {
			objectFit: "cover"
	},
	opacity0: {
			opacity: "0%"
	},
	opacity100: {
			opacity: "100%"
	},
	opacity40: {
			opacity: "40%"
	},
	opacity55: {
			opacity: "55%"
	},
	opacity60: {
			opacity: "60%"
	},
	opacity85: {
			opacity: "85%"
	},
	order1: {
			order: "1"
	},
	order2: {
			order: "2"
	},
	order3: {
			order: "3"
	},
	order4: {
			order: "4"
	},
	order5: {
			order: "5"
	},
	outlineDivider: {
			outlineColor: "var(--divider)"
	},
	outlineNone: {
			outlineStyle: "none"
	},
	overflowHidden: {
			overflow: "hidden"
	},
	overflowXAuto: {
			overflowX: "auto"
	},
	overflowXHidden: {
			overflowX: "hidden"
	},
	overflowYAuto: {
			overflowY: "auto"
	},
	overflowYHidden: {
			overflowY: "hidden"
	},
	overflowYVisible: {
			overflowY: "visible"
	},
	overscrollContain: {
			overscrollBehavior: "contain"
	},
	p0: {
			padding: "0"
	},
	p1: {
			padding: "4px"
	},
	p2: {
			padding: "calc(4px * 2)"
	},
	p5: {
			padding: "calc(4px * 5)"
	},
	p6: {
			padding: "calc(4px * 6)"
	},
	pb0: {
			paddingBottom: "0"
	},
	pb05: {
			paddingBottom: "calc(4px * 0.5)"
	},
	pb1: {
			paddingBottom: "4px"
	},
	pb15: {
			paddingBottom: "calc(4px * 1.5)"
	},
	pb10: {
			paddingBottom: "calc(4px * 10)"
	},
	pb12: {
			paddingBottom: "calc(4px * 12)"
	},
	pb2: {
			paddingBottom: "calc(4px * 2)"
	},
	pb25: {
			paddingBottom: "calc(4px * 2.5)"
	},
	pb22: {
			paddingBottom: "calc(4px * 22)"
	},
	pb35: {
			paddingBottom: "calc(4px * 3.5)"
	},
	pb5: {
			paddingBottom: "calc(4px * 5)"
	},
	pb7: {
			paddingBottom: "calc(4px * 7)"
	},
	pb26px: {
			paddingBottom: "26px"
	},
	pb5px: {
			paddingBottom: "5px"
	},
	pbCalcVarSessionUnderVarSuggestionsUnder0px16px: {
			paddingBottom: "calc(var(--session-under) + var(--suggestions-under,0px) + 16px)"
	},
	pbMax16pxEnvSafeAreaInsetBottom0px: {
			paddingBottom: "max(16px, env(safe-area-inset-bottom,0px))"
	},
	pbMax24pxEnvSafeAreaInsetBottom0px: {
			paddingBottom: "max(24px, env(safe-area-inset-bottom,0px))"
	},
	phoneBeforeInsetX3: {
			"@media (max-width: 720px)": {
					"::before": {
							content: "\"\"",
							insetInline: "calc(4px * -3)"
					}
			}
	},
	phoneBeforeTop15: {
			"@media (max-width: 720px)": {
					"::before": {
							content: "\"\"",
							top: "calc(4px * -1.5)"
					}
			}
	},
	phoneBgClipContent: {
			"@media (max-width: 720px)": {
					backgroundClip: "content-box"
			}
	},
	phoneBorderL0: {
			"@media (max-width: 720px)": {
					borderLeftStyle: "solid",
					borderLeftWidth: "0px"
			}
	},
	phoneBorderT: {
			"@media (max-width: 720px)": {
					borderTopStyle: "solid",
					borderTopWidth: "1px"
			}
	},
	phoneBottomAuto: {
			"@media (max-width: 720px)": {
					bottom: "auto"
			}
	},
	phoneColStart2: {
			"@media (max-width: 720px)": {
					gridColumnStart: "2"
			}
	},
	phoneColStart3: {
			"@media (max-width: 720px)": {
					gridColumnStart: "3"
			}
	},
	phoneDurationVarDurLg: {
			"@media (max-width: 720px)": {
					transitionDuration: "var(--dur-lg)"
			}
	},
	phoneEaseVarEase: {
			"@media (max-width: 720px)": {
					transitionTimingFunction: "var(--ease)"
			}
	},
	phoneFlex: {
			"@media (max-width: 720px)": {
					display: "flex"
			}
	},
	phoneFlexCol: {
			"@media (max-width: 720px)": {
					flexDirection: "column"
			}
	},
	phoneFlexColReverse: {
			"@media (max-width: 720px)": {
					flexDirection: "column-reverse"
			}
	},
	phoneGap15: {
			"@media (max-width: 720px)": {
					gap: "calc(4px * 1.5)"
			}
	},
	phoneGap2: {
			"@media (max-width: 720px)": {
					gap: "calc(4px * 2)"
			}
	},
	phoneGap3: {
			"@media (max-width: 720px)": {
					gap: "calc(4px * 3)"
			}
	},
	phoneGapX2: {
			"@media (max-width: 720px)": {
					columnGap: "calc(4px * 2)"
			}
	},
	phoneGapY0: {
			"@media (max-width: 720px)": {
					rowGap: "0"
			}
	},
	phoneGridCols1: {
			"@media (max-width: 720px)": {
					gridTemplateColumns: "repeat(1, minmax(0, 1fr))"
			}
	},
	phoneGridCols2: {
			"@media (max-width: 720px)": {
					gridTemplateColumns: "repeat(2, minmax(0, 1fr))"
			}
	},
	phoneGridColsMinmax01fr72pxMinmax38pxAuto: {
			"@media (max-width: 720px)": {
					gridTemplateColumns: "minmax(0,1fr) 72px minmax(38px,auto)"
			}
	},
	phoneH11: {
			"@media (max-width: 720px)": {
					height: "calc(4px * 11)"
			}
	},
	phoneHFull: {
			"@media (max-width: 720px)": {
					height: "100%"
			}
	},
	phoneHidden: {
			"@media (max-width: 720px)": {
					display: "none"
			}
	},
	phoneInline: {
			"@media (max-width: 720px)": {
					display: "inline"
			}
	},
	phoneInlineFlex: {
			"@media (max-width: 720px)": {
					display: "inline-flex"
			}
	},
	phoneInsetX0: {
			"@media (max-width: 720px)": {
					insetInline: "0"
			}
	},
	phoneItemsCenter: {
			"@media (max-width: 720px)": {
					alignItems: "center"
			}
	},
	phoneItemsStart: {
			"@media (max-width: 720px)": {
					alignItems: "flex-start"
			}
	},
	phoneItemsStretch: {
			"@media (max-width: 720px)": {
					alignItems: "stretch"
			}
	},
	phoneJustifyEnd: {
			"@media (max-width: 720px)": {
					justifyContent: "flex-end"
			}
	},
	phoneMaxH240px: {
			"@media (max-width: 720px)": {
					maxHeight: "240px"
			}
	},
	phoneMaxHNone: {
			"@media (max-width: 720px)": {
					maxHeight: "none"
			}
	},
	phoneMaxW136px: {
			"@media (max-width: 720px)": {
					maxWidth: "136px"
			}
	},
	phoneMaxWNone: {
			"@media (max-width: 720px)": {
					maxWidth: "none"
			}
	},
	phoneMb6: {
			"@media (max-width: 720px)": {
					marginBottom: "calc(4px * 6)"
			}
	},
	phoneMinH0: {
			"@media (max-width: 720px)": {
					minHeight: "0"
			}
	},
	phoneMinH10: {
			"@media (max-width: 720px)": {
					minHeight: "calc(4px * 10)"
			}
	},
	phoneMinH11: {
			"@media (max-width: 720px)": {
					minHeight: "calc(4px * 11)"
			}
	},
	phoneMinH12: {
			"@media (max-width: 720px)": {
					minHeight: "calc(4px * 12)"
			}
	},
	phoneMinH14: {
			"@media (max-width: 720px)": {
					minHeight: "calc(4px * 14)"
			}
	},
	phoneMlAuto: {
			"@media (max-width: 720px)": {
					marginLeft: "auto"
			}
	},
	phoneMt0: {
			"@media (max-width: 720px)": {
					marginTop: "0"
			}
	},
	phoneMt15: {
			"@media (max-width: 720px)": {
					marginTop: "calc(4px * 1.5)"
			}
	},
	phoneMy3: {
			"@media (max-width: 720px)": {
					marginBlock: "calc(4px * 3)"
			}
	},
	phoneOrder1: {
			"@media (max-width: 720px)": {
					order: "-1"
			}
	},
	phoneOrder2: {
			"@media (max-width: 720px)": {
					order: "-2"
			}
	},
	phoneOverflowVisible: {
			"@media (max-width: 720px)": {
					overflow: "visible"
			}
	},
	phoneP1: {
			"@media (max-width: 720px)": {
					padding: "4px"
			}
	},
	phoneP35: {
			"@media (max-width: 720px)": {
					padding: "calc(4px * 3.5)"
			}
	},
	phoneP4: {
			"@media (max-width: 720px)": {
					padding: "calc(4px * 4)"
			}
	},
	phoneP5: {
			"@media (max-width: 720px)": {
					padding: "calc(4px * 5)"
			}
	},
	phoneP6: {
			"@media (max-width: 720px)": {
					padding: "calc(4px * 6)"
			}
	},
	phonePb0: {
			"@media (max-width: 720px)": {
					paddingBottom: "0"
			}
	},
	phonePb1: {
			"@media (max-width: 720px)": {
					paddingBottom: "4px"
			}
	},
	phonePb12: {
			"@media (max-width: 720px)": {
					paddingBottom: "calc(4px * 12)"
			}
	},
	phonePb9px: {
			"@media (max-width: 720px)": {
					paddingBottom: "9px"
			}
	},
	phonePbMax12pxEnvSafeAreaInsetBottom: {
			"@media (max-width: 720px)": {
					paddingBottom: "max(12px, env(safe-area-inset-bottom))"
			}
	},
	phonePbMax16pxEnvSafeAreaInsetBottom0px: {
			"@media (max-width: 720px)": {
					paddingBottom: "max(16px, env(safe-area-inset-bottom,0px))"
			}
	},
	phonePl2: {
			"@media (max-width: 720px)": {
					paddingLeft: "calc(4px * 2)"
			}
	},
	phonePl35: {
			"@media (max-width: 720px)": {
					paddingLeft: "calc(4px * 3.5)"
			}
	},
	phonePl10px: {
			"@media (max-width: 720px)": {
					paddingLeft: "10px"
			}
	},
	phonePl17px: {
			"@media (max-width: 720px)": {
					paddingLeft: "17px"
			}
	},
	phonePr0: {
			"@media (max-width: 720px)": {
					paddingRight: "0"
			}
	},
	phonePr05: {
			"@media (max-width: 720px)": {
					paddingRight: "calc(4px * 0.5)"
			}
	},
	phonePt0: {
			"@media (max-width: 720px)": {
					paddingTop: "0"
			}
	},
	phonePt25: {
			"@media (max-width: 720px)": {
					paddingTop: "calc(4px * 2.5)"
			}
	},
	phonePt3: {
			"@media (max-width: 720px)": {
					paddingTop: "calc(4px * 3)"
			}
	},
	phonePt4: {
			"@media (max-width: 720px)": {
					paddingTop: "calc(4px * 4)"
			}
	},
	phonePt5: {
			"@media (max-width: 720px)": {
					paddingTop: "calc(4px * 5)"
			}
	},
	phonePt6: {
			"@media (max-width: 720px)": {
					paddingTop: "calc(4px * 6)"
			}
	},
	phonePtCalcVarPaneHeaderHVarStripClearance0px: {
			"@media (max-width: 720px)": {
					paddingTop: "calc(var(--pane-header-h) + var(--strip-clearance,0px))"
			}
	},
	phonePtCalcVarPaneHeaderHVarStripClearance0px8px: {
			"@media (max-width: 720px)": {
					paddingTop: "calc(var(--pane-header-h) + var(--strip-clearance,0px) + 8px)"
			}
	},
	phonePtMax12pxEnvSafeAreaInsetTop: {
			"@media (max-width: 720px)": {
					paddingTop: "max(12px, env(safe-area-inset-top))"
			}
	},
	phonePx0: {
			"@media (max-width: 720px)": {
					paddingInline: "0"
			}
	},
	phonePx2: {
			"@media (max-width: 720px)": {
					paddingInline: "calc(4px * 2)"
			}
	},
	phonePx3: {
			"@media (max-width: 720px)": {
					paddingInline: "calc(4px * 3)"
			}
	},
	phonePx4: {
			"@media (max-width: 720px)": {
					paddingInline: "calc(4px * 4)"
			}
	},
	phonePx5: {
			"@media (max-width: 720px)": {
					paddingInline: "calc(4px * 5)"
			}
	},
	phonePx9px: {
			"@media (max-width: 720px)": {
					paddingInline: "9px"
			}
	},
	phonePy4: {
			"@media (max-width: 720px)": {
					paddingBlock: "calc(4px * 4)"
			}
	},
	phonePy13px: {
			"@media (max-width: 720px)": {
					paddingBlock: "13px"
			}
	},
	phonePy7px: {
			"@media (max-width: 720px)": {
					paddingBlock: "7px"
			}
	},
	phoneRight0: {
			"@media (max-width: 720px)": {
					right: "0"
			}
	},
	phoneRoundedLg: {
			"@media (max-width: 720px)": {
					borderRadius: "calc(14px * var(--rf))",
					cornerShape: "var(--cs)"
			}
	},
	phoneRoundedNone: {
			"@media (max-width: 720px)": {
					borderRadius: "0",
					cornerShape: "var(--cs)"
			}
	},
	phoneRowStart1: {
			"@media (max-width: 720px)": {
					gridRowStart: "1"
			}
	},
	phoneSelfStretch: {
			"@media (max-width: 720px)": {
					alignSelf: "stretch"
			}
	},
	phoneSize10: {
			"@media (max-width: 720px)": {
					width: "calc(4px * 10)",
					height: "calc(4px * 10)"
			}
	},
	phoneSize11: {
			"@media (max-width: 720px)": {
					width: "calc(4px * 11)",
					height: "calc(4px * 11)"
			}
	},
	phoneTextBase: {
			"@media (max-width: 720px)": {
					fontSize: "var(--type-body)",
					lineHeight: "var(--tw-leading, var(--text-base--line-height))"
			}
	},
	phoneTextInputPhone: {
			"@media (max-width: 720px)": {
					fontSize: "var(--type-input-phone)"
			}
	},
	phoneTextLabel: {
			"@media (max-width: 720px)": {
					fontSize: "var(--type-label)"
			}
	},
	phoneTextSectionTitle: {
			"@media (max-width: 720px)": {
					fontSize: "var(--type-section-title)"
			}
	},
	phoneTopCalcVarHeaderH8px: {
			"@media (max-width: 720px)": {
					top: "calc(var(--header-h) + 8px)"
			}
	},
	phoneTopCalcVarPaneHeaderHVarStripClearance0px8px: {
			"@media (max-width: 720px)": {
					top: "calc(var(--pane-header-h) + var(--strip-clearance,0px) + 8px)"
			}
	},
	phoneW9: {
			"@media (max-width: 720px)": {
					width: "calc(4px * 9)"
			}
	},
	phoneWFull: {
			"@media (max-width: 720px)": {
					width: "100%"
			}
	},
	phoneWhitespaceNormal: {
			"@media (max-width: 720px)": {
					whiteSpace: "normal"
			}
	},
	pl0: {
			paddingLeft: "0"
	},
	pl05: {
			paddingLeft: "calc(4px * 0.5)"
	},
	pl15: {
			paddingLeft: "calc(4px * 1.5)"
	},
	pl2: {
			paddingLeft: "calc(4px * 2)"
	},
	pl25: {
			paddingLeft: "calc(4px * 2.5)"
	},
	pl3: {
			paddingLeft: "calc(4px * 3)"
	},
	pl19px: {
			paddingLeft: "19px"
	},
	plCalcVarSidebarIconLeft8px: {
			paddingLeft: "calc(var(--sidebar-icon-left) - 8px)"
	},
	plCalcVarSidebarIconLeft16pxVarSidebarNavX6px: {
			paddingLeft: "calc(var(--sidebar-icon-left,16px) - var(--sidebar-nav-x,6px))"
	},
	placeItemsCenter: {
			placeItems: "center"
	},
	placeholderTextColorMixInSrgbVarTextFaint84VarYellow: {
			"::placeholder": {
					color: "color-mix(in srgb,var(--text-faint) 84%,var(--yellow))"
			}
	},
	placeholderTextFaint: {
			"::placeholder": {
					color: "var(--text-faint)"
			}
	},
	pointerEventsAuto: {
			pointerEvents: "auto"
	},
	pointerEventsNone: {
			pointerEvents: "none"
	},
	pr05: {
			paddingRight: "calc(4px * 0.5)"
	},
	pr1: {
			paddingRight: "4px"
	},
	pr15: {
			paddingRight: "calc(4px * 1.5)"
	},
	pr2: {
			paddingRight: "calc(4px * 2)"
	},
	pr3: {
			paddingRight: "calc(4px * 3)"
	},
	pr35: {
			paddingRight: "calc(4px * 3.5)"
	},
	pr5: {
			paddingRight: "calc(4px * 5)"
	},
	pr26px: {
			paddingRight: "26px"
	},
	pr7px: {
			paddingRight: "7px"
	},
	pt0: {
			paddingTop: "0"
	},
	pt05: {
			paddingTop: "calc(4px * 0.5)"
	},
	pt1: {
			paddingTop: "4px"
	},
	pt11: {
			paddingTop: "calc(4px * 11)"
	},
	pt2: {
			paddingTop: "calc(4px * 2)"
	},
	pt25: {
			paddingTop: "calc(4px * 2.5)"
	},
	pt3: {
			paddingTop: "calc(4px * 3)"
	},
	pt35: {
			paddingTop: "calc(4px * 3.5)"
	},
	pt4: {
			paddingTop: "calc(4px * 4)"
	},
	pt5: {
			paddingTop: "calc(4px * 5)"
	},
	pt9px: {
			paddingTop: "9px"
	},
	ptEnvSafeAreaInsetTop0px: {
			paddingTop: "env(safe-area-inset-top,0px)"
	},
	ptVarHeaderH: {
			paddingTop: "var(--header-h)"
	},
	ptPx: {
			paddingTop: "1px"
	},
	px0: {
			paddingInline: "0"
	},
	px05: {
			paddingInline: "calc(4px * 0.5)"
	},
	px1: {
			paddingInline: "4px"
	},
	px15: {
			paddingInline: "calc(4px * 1.5)"
	},
	px10: {
			paddingInline: "calc(4px * 10)"
	},
	px2: {
			paddingInline: "calc(4px * 2)"
	},
	px25: {
			paddingInline: "calc(4px * 2.5)"
	},
	px3: {
			paddingInline: "calc(4px * 3)"
	},
	px35: {
			paddingInline: "calc(4px * 3.5)"
	},
	px352: {
			paddingInline: "calc(4px * 3.5) !important"
	},
	px4: {
			paddingInline: "calc(4px * 4)"
	},
	px5: {
			paddingInline: "calc(4px * 5)"
	},
	px6: {
			paddingInline: "calc(4px * 6)"
	},
	px8: {
			paddingInline: "calc(4px * 8)"
	},
	px11px: {
			paddingInline: "11px"
	},
	px13px: {
			paddingInline: "13px"
	},
	px16px: {
			paddingInline: "16px"
	},
	px5px: {
			paddingInline: "5px"
	},
	px6px: {
			paddingInline: "6px"
	},
	px9px: {
			paddingInline: "9px"
	},
	pxCalcVarSidebarIconLeftVarSidebarNavX: {
			paddingInline: "calc(var(--sidebar-icon-left) - var(--sidebar-nav-x))"
	},
	pxVarSidebarNavX: {
			paddingInline: "var(--sidebar-nav-x)"
	},
	py0: {
			paddingBlock: "0"
	},
	py05: {
			paddingBlock: "calc(4px * 0.5)"
	},
	py1: {
			paddingBlock: "4px"
	},
	py15: {
			paddingBlock: "calc(4px * 1.5)"
	},
	py2: {
			paddingBlock: "calc(4px * 2)"
	},
	py25: {
			paddingBlock: "calc(4px * 2.5)"
	},
	py35: {
			paddingBlock: "calc(4px * 3.5)"
	},
	py4: {
			paddingBlock: "calc(4px * 4)"
	},
	py3px: {
			paddingBlock: "3px"
	},
	py5px: {
			paddingBlock: "5px"
	},
	py7px: {
			paddingBlock: "7px"
	},
	py9px: {
			paddingBlock: "9px"
	},
	pyVarSidebarToolPad: {
			paddingBlock: "var(--sidebar-tool-pad)"
	},
	pyPx: {
			paddingBlock: "1px"
	},
	relative: {
			position: "relative"
	},
	resizeNone: {
			resize: "none"
	},
	resizeY: {
			resize: "vertical"
	},
	right0: {
			right: "0"
	},
	right14: {
			right: "calc(4px * 14)"
	},
	right3: {
			right: "calc(4px * 3)"
	},
	right4: {
			right: "calc(4px * 4)"
	},
	right3px: {
			right: "-3px"
	},
	right5px: {
			right: "5px"
	},
	right7px: {
			right: "7px"
	},
	rotate180: {
			rotate: "180deg"
	},
	rounded2xl: {
			borderRadius: "calc(22px * var(--rf))",
			cornerShape: "var(--cs)"
	},
	rounded999px: {
			borderRadius: "999px",
			cornerShape: "var(--cs)"
	},
	roundedCalc6pxVarRf: {
			borderRadius: "calc(6px * var(--rf))",
			cornerShape: "var(--cs)"
	},
	roundedCalc8pxVarRf: {
			borderRadius: "calc(8px * var(--rf))",
			cornerShape: "var(--cs)"
	},
	roundedVarComposerRadius: {
			borderRadius: "var(--composer-radius)",
			cornerShape: "var(--cs)"
	},
	roundedControl: {
			borderRadius: "calc(12px * var(--rf))",
			cornerShape: "var(--cs)"
	},
	roundedFull: {
			borderRadius: "calc(infinity * 1px)",
			cornerShape: "round"
	},
	roundedLg: {
			borderRadius: "calc(14px * var(--rf))",
			cornerShape: "var(--cs)"
	},
	roundedMd: {
			borderRadius: "calc(7px * var(--rf))",
			cornerShape: "var(--cs)"
	},
	roundedRow: {
			borderRadius: "calc(12px * var(--rf))",
			cornerShape: "var(--cs)"
	},
	roundedSection: {
			borderRadius: "calc(28px * var(--rf))",
			cornerShape: "var(--cs)"
	},
	roundedSm: {
			borderRadius: "calc(4px * var(--rf))",
			cornerShape: "var(--cs)"
	},
	roundedTVarComposerRadius: {
			borderTopLeftRadius: "var(--composer-radius)",
			borderTopRightRadius: "var(--composer-radius)",
			cornerShape: "var(--cs)"
	},
	roundedXl: {
			borderRadius: "calc(18px * var(--rf))",
			cornerShape: "var(--cs)"
	},
	scrollMt4: {
			scrollMarginTop: "calc(4px * 4)"
	},
	selectAll: {
			WebkitUserSelect: "all",
			userSelect: "all"
	},
	selectNone: {
			WebkitUserSelect: "none",
			userSelect: "none"
	},
	selectText: {
			WebkitUserSelect: "text",
			userSelect: "text"
	},
	selfCenter: {
			alignSelf: "center"
	},
	selfStart: {
			alignSelf: "flex-start"
	},
	selfStretch: {
			alignSelf: "stretch"
	},
	shrink: {
			flexShrink: "1"
	},
	shrink0: {
			flexShrink: "0"
	},
	size15: {
			width: "calc(4px * 1.5)",
			height: "calc(4px * 1.5)"
	},
	size10: {
			width: "calc(4px * 10)",
			height: "calc(4px * 10)"
	},
	size11: {
			width: "calc(4px * 11)",
			height: "calc(4px * 11)"
	},
	size14: {
			width: "calc(4px * 14)",
			height: "calc(4px * 14)"
	},
	size16: {
			width: "calc(4px * 16)",
			height: "calc(4px * 16)"
	},
	size3: {
			width: "calc(4px * 3)",
			height: "calc(4px * 3)"
	},
	size4: {
			width: "calc(4px * 4)",
			height: "calc(4px * 4)"
	},
	size5: {
			width: "calc(4px * 5)",
			height: "calc(4px * 5)"
	},
	size7: {
			width: "calc(4px * 7)",
			height: "calc(4px * 7)"
	},
	size8: {
			width: "calc(4px * 8)",
			height: "calc(4px * 8)"
	},
	size9: {
			width: "calc(4px * 9)",
			height: "calc(4px * 9)"
	},
	size18px: {
			width: "18px",
			height: "18px"
	},
	size22px: {
			width: "22px",
			height: "22px"
	},
	size34px: {
			width: "34px",
			height: "34px"
	},
	size38px: {
			width: "38px",
			height: "38px"
	},
	size7px: {
			width: "7px",
			height: "7px"
	},
	sizeFull: {
			width: "100%",
			height: "100%"
	},
	smGridCols2: {
			"@media (min-width: 40rem)": {
					gridTemplateColumns: "repeat(2, minmax(0, 1fr))"
			}
	},
	snapStart: {
			scrollSnapAlign: "start"
	},
	sticky: {
			position: "sticky"
	},
	text17130a: {
			color: "#17130a"
	},
	text5eead4: {
			color: "#5eead4"
	},
	text7b86e8: {
			color: "#7b86e8"
	},
	text10px: {
			fontSize: "10px"
	},
	text15px: {
			fontSize: "15px"
	},
	text20px: {
			fontSize: "20px"
	},
	text22px: {
			fontSize: "22px"
	},
	textColorMixInSrgbVarText881f9e8a: {
			color: "color-mix(in srgb,var(--text) 88%,#1f9e8a)"
	},
	textInherit: {
			color: "inherit"
	},
	textBase: {
			fontSize: "var(--type-body) !important",
			lineHeight: "var(--tw-leading, var(--text-base--line-height)) !important"
	},
	textBg: {
			color: "var(--bg)"
	},
	textCenter: {
			textAlign: "center"
	},
	textDim: {
			color: "var(--text-dim)"
	},
	textEllipsis: {
			textOverflow: "ellipsis"
	},
	textFg: {
			color: "var(--text)"
	},
	textFg65: {
			color: "color-mix(in oklab, var(--text) 65%, transparent)"
	},
	textInherit2: {
			color: "inherit"
	},
	textLeft: {
			textAlign: "left"
	},
	textOnAccent: {
			color: "var(--on-accent)"
	},
	textPanel: {
			color: "var(--bg-panel)"
	},
	textRed: {
			color: "var(--red)"
	},
	textRight: {
			textAlign: "right"
	},
	textTransparent: {
			color: "transparent"
	},
	textWhite: {
			color: "var(--color-white)"
	},
	top0: {
			top: "0"
	},
	top12: {
			top: "calc(1 / 2 * 100%)"
	},
	topCalcVarDesktopHeaderH35px2: {
			top: "calc((var(--desktop-header-h) - 35px) / 2)"
	},
	topCalcVarDesktopHeaderH8px: {
			top: "calc(var(--desktop-header-h) + 8px)"
	},
	touchNone: {
			touchAction: "none"
	},
	tracking001em: {
			letterSpacing: "-0.01em"
	},
	tracking002em: {
			letterSpacing: "-0.02em"
	},
	tracking002em2: {
			letterSpacing: "0.02em"
	},
	transformTranslateXVarSwipeX0: {
			transform: "translateX(var(--swipe-x,0))"
	},
	transitionBackgroundColorBorderColorColorFilterScale: {
			transitionProperty: "background-color,border-color,color,filter,scale",
			transitionTimingFunction: "var(--tw-ease, var(--ease))",
			transitionDuration: "var(--tw-duration, var(--dur-micro))"
	},
	transitionBackgroundColorColorScale: {
			transitionProperty: "background-color,color,scale",
			transitionTimingFunction: "var(--tw-ease, var(--ease))",
			transitionDuration: "var(--tw-duration, var(--dur-micro))"
	},
	transitionBackgroundColorScale: {
			transitionProperty: "background-color,scale",
			transitionTimingFunction: "var(--tw-ease, var(--ease))",
			transitionDuration: "var(--tw-duration, var(--dur-micro))"
	},
	transitionBackgroundColor: {
			transitionProperty: "background-color",
			transitionTimingFunction: "var(--tw-ease, var(--ease))",
			transitionDuration: "var(--tw-duration, var(--dur-micro))"
	},
	transitionBorderColorBoxShadow: {
			transitionProperty: "border-color,box-shadow",
			transitionTimingFunction: "var(--tw-ease, var(--ease))",
			transitionDuration: "var(--tw-duration, var(--dur-micro))"
	},
	transitionBorderColorScale: {
			transitionProperty: "border-color,scale",
			transitionTimingFunction: "var(--tw-ease, var(--ease))",
			transitionDuration: "var(--tw-duration, var(--dur-micro))"
	},
	transitionColorBackgroundColorScale: {
			transitionProperty: "color,background-color,scale",
			transitionTimingFunction: "var(--tw-ease, var(--ease))",
			transitionDuration: "var(--tw-duration, var(--dur-micro))"
	},
	transitionColorBackground: {
			transitionProperty: "color,background",
			transitionTimingFunction: "var(--tw-ease, var(--ease))",
			transitionDuration: "var(--tw-duration, var(--dur-micro))"
	},
	transitionColorOpacityBackground: {
			transitionProperty: "color,opacity,background",
			transitionTimingFunction: "var(--tw-ease, var(--ease))",
			transitionDuration: "var(--tw-duration, var(--dur-micro))"
	},
	transitionColorScale: {
			transitionProperty: "color,scale",
			transitionTimingFunction: "var(--tw-ease, var(--ease))",
			transitionDuration: "var(--tw-duration, var(--dur-micro))"
	},
	transitionOpacityColor: {
			transitionProperty: "opacity,color",
			transitionTimingFunction: "var(--tw-ease, var(--ease))",
			transitionDuration: "var(--tw-duration, var(--dur-micro))"
	},
	transitionOpacityTransform: {
			transitionProperty: "opacity,transform",
			transitionTimingFunction: "var(--tw-ease, var(--ease))",
			transitionDuration: "var(--tw-duration, var(--dur-micro))"
	},
	transitionScale: {
			transitionProperty: "scale",
			transitionTimingFunction: "var(--tw-ease, var(--ease))",
			transitionDuration: "var(--tw-duration, var(--dur-micro))"
	},
	transitionTransformFilter: {
			transitionProperty: "transform,filter",
			transitionTimingFunction: "var(--tw-ease, var(--ease))",
			transitionDuration: "var(--tw-duration, var(--dur-micro))"
	},
	transitionTransformOpacity: {
			transitionProperty: "transform,opacity",
			transitionTimingFunction: "var(--tw-ease, var(--ease))",
			transitionDuration: "var(--tw-duration, var(--dur-micro))"
	},
	transitionWidthBackgroundColorOpacity: {
			transitionProperty: "width,background-color,opacity",
			transitionTimingFunction: "var(--tw-ease, var(--ease))",
			transitionDuration: "var(--tw-duration, var(--dur-micro))"
	},
	transitionWidthHeight: {
			transitionProperty: "width,height",
			transitionTimingFunction: "var(--tw-ease, var(--ease))",
			transitionDuration: "var(--tw-duration, var(--dur-micro))"
	},
	transitionWidth: {
			transitionProperty: "width",
			transitionTimingFunction: "var(--tw-ease, var(--ease))",
			transitionDuration: "var(--tw-duration, var(--dur-micro))"
	},
	transitionColors: {
			transitionProperty: "color, background-color, border-color, outline-color, text-decoration-color, fill, stroke, --tw-gradient-from, --tw-gradient-via, --tw-gradient-to",
			transitionTimingFunction: "var(--tw-ease, var(--ease))",
			transitionDuration: "var(--tw-duration, var(--dur-micro))"
	},
	transitionNone: {
			transitionProperty: "none"
	},
	transitionOpacity: {
			transitionProperty: "opacity",
			transitionTimingFunction: "var(--tw-ease, var(--ease))",
			transitionDuration: "var(--tw-duration, var(--dur-micro))"
	},
	transitionTransform: {
			transitionProperty: "transform, translate, scale, rotate",
			transitionTimingFunction: "var(--tw-ease, var(--ease))",
			transitionDuration: "var(--tw-duration, var(--dur-micro))"
	},
	translateXCalc50VarWsSummaryStep0px: {
			translate: "calc(-50% + var(--ws-summary-step,0px)) 0"
	},
	truncate: {
			overflow: "hidden",
			textOverflow: "ellipsis",
			whiteSpace: "nowrap"
	},
	visible: {
			visibility: "visible"
	},
	w2: {
			width: "calc(4px * 2)"
	},
	w21: {
			width: "calc(4px * 21)"
	},
	w5: {
			width: "calc(4px * 5)"
	},
	w6: {
			width: "calc(4px * 6)"
	},
	w7: {
			width: "calc(4px * 7)"
	},
	w140px: {
			width: "140px"
	},
	w220px: {
			width: "220px"
	},
	w300px: {
			width: "300px"
	},
	w46px: {
			width: "46px"
	},
	w7px: {
			width: "7px"
	},
	wCalc10030px2: {
			width: "calc((100% - 30px) / 2)"
	},
	wCalc10012px: {
			width: "calc(100% + 12px)"
	},
	wCalc10016px: {
			width: "calc(100% - 16px)"
	},
	wMin1040pxCalc100vw32px: {
			width: "min(1040px, calc(100vw - 32px))"
	},
	wMin1280px92vw: {
			width: "min(1280px, 92vw)"
	},
	wMin640px100: {
			width: "min(640px, 100%)"
	},
	wMin880pxCalc100vw32px: {
			width: "min(880px, calc(100vw - 32px))"
	},
	wVarSidebarW280px: {
			width: "var(--sidebar-w,280px)"
	},
	wVarSwipeActionW82px: {
			width: "var(--swipe-action-w,82px)"
	},
	wAuto: {
			width: "auto"
	},
	wFit: {
			width: "fit-content"
	},
	wFull: {
			width: "100%"
	},
	wFull2: {
			width: "100% !important"
	},
	whitespaceNowrap: {
			whiteSpace: "nowrap"
	},
	whitespacePreWrap: {
			whiteSpace: "pre-wrap"
	},
	willChangeWidth: {
			willChange: "width"
	},
	willChangeTransform: {
			willChange: "transform"
	},
	z0: {
			zIndex: "0"
	},
	z1: {
			zIndex: "1"
	},
	z10: {
			zIndex: "10"
	},
	z20: {
			zIndex: "20"
	},
	z30: {
			zIndex: "30"
	},
	z40: {
			zIndex: "40"
	},
	z12: {
			zIndex: "1"
	},
	z200: {
			zIndex: "200"
	},
	z2147483646: {
			zIndex: "2147483646"
	},
	z4: {
			zIndex: "4"
	},
	z5: {
			zIndex: "5"
	},
	z60: {
			zIndex: "60"
	},
	z9500: {
			zIndex: "9500"
	},
});

export const utilityStyles = {
	"-bottom-1": sx.Bottom1,
	"-mb-2.5": sx.Mb25,
	"-mb-3.5": sx.Mb35,
	"-ml-1": sx.Ml1,
	"-ml-1.5": sx.Ml15,
	"-ml-2": sx.Ml2,
	"-mt-[11px]": sx.Mt11px,
	"-mx-2": sx.Mx2,
	"-mx-[6px]": sx.Mx6px,
	"-my-1": sx.My1,
	"-my-[5px]": sx.My5px,
	"-right-1": sx.Right1,
	"-rotate-90": sx.Rotate90,
	"-translate-y-1/2": sx.TranslateY12,
	"-translate-y-px": sx.TranslateYPx,
	"absolute": sx.absolute,
	"active:cursor-grabbing": sx.activeCursorGrabbing,
	"active:scale-[0.96]": sx.activeScale096,
	"active:scale-[0.98]": sx.activeScale098,
	"after:-inset-x-1": sx.afterInsetX1,
	"after:absolute": sx.afterAbsolute,
	"after:bg-accent": sx.afterBgAccent,
	"after:bg-transparent": sx.afterBgTransparent,
	"after:border-l": sx.afterBorderL,
	"after:border-transparent": sx.afterBorderTransparent,
	"after:content-['']": sx.afterContent,
	"after:h-full": sx.afterHFull,
	"after:inset-y-0": sx.afterInsetY0,
	"after:left-1/2": sx.afterLeft12,
	"after:right-[3px]": sx.afterRight3px,
	"after:right-[5px]": sx.afterRight5px,
	"after:rounded-full": sx.afterRoundedFull,
	"after:size-1.5": sx.afterSize15,
	"after:top-0": sx.afterTop0,
	"after:top-[5px]": sx.afterTop5px,
	"after:transition-[background]": sx.afterTransitionBackground,
	"after:transition-colors": sx.afterTransitionColors,
	"after:w-[2px]": sx.afterW2px,
	"animate-[pulse_1.2s_ease-in-out_infinite]": sx.animatePulse12sEaseInOutInfinite,
	"animate-[pulse_1.4s_ease-in-out_infinite]": sx.animatePulse14sEaseInOutInfinite,
	"animate-[text-shimmer_1.8s_linear_infinite]": sx.animateTextShimmer18sLinearInfinite,
	"animate-[update-toast-in_var(--dur-lg)_var(--ease)]": sx.animateUpdateToastInVarDurLgVarEase,
	"animate-pulse": sx.animatePulse,
	"animate-spin": sx.animateSpin,
	"aspect-square": sx.aspectSquare,
	"aspect-video": sx.aspectVideo,
	"before:-inset-x-3.5": sx.beforeInsetX35,
	"before:-top-2.5": sx.beforeTop25,
	"before:-translate-x-1/2": sx.beforeTranslateX12,
	"before:-translate-y-1/2": sx.beforeTranslateY12,
	"before:[corner-shape:inherit]": sx.beforeCornerShapeInherit,
	"before:[corner-shape:var(--cs)]": sx.beforeCornerShapeVarCs,
	"before:absolute": sx.beforeAbsolute,
	"before:bg-[var(--composer-note-bg)]": sx.beforeBgVarComposerNoteBg,
	"before:bg-divider": sx.beforeBgDivider,
	"before:bg-transparent": sx.beforeBgTransparent,
	"before:content-['']": sx.beforeContent,
	"before:duration-150": sx.beforeDuration150,
	"before:ease-[cubic-bezier(0.32,0.72,0,1)]": sx.beforeEaseCubicBezier03207201,
	"before:h-px": sx.beforeHPx,
	"before:inset-0": sx.beforeInset0,
	"before:inset-0.5": sx.beforeInset05,
	"before:inset-2": sx.beforeInset2,
	"before:inset-[3px]": sx.beforeInset3px,
	"before:left-1/2": sx.beforeLeft12,
	"before:opacity-0": sx.beforeOpacity0,
	"before:opacity-100": sx.beforeOpacity100,
	"before:pointer-events-none": sx.beforePointerEventsNone,
	"before:rounded-[calc(6px*var(--rf))]": sx.beforeRoundedCalc6pxVarRf,
	"before:rounded-[calc(9px*var(--rf))]": sx.beforeRoundedCalc9pxVarRf,
	"before:rounded-[inherit]": sx.beforeRoundedInherit,
	"before:rounded-md": sx.beforeRoundedMd,
	"before:rounded-sm": sx.beforeRoundedSm,
	"before:size-7": sx.beforeSize7,
	"before:text-meta": sx.beforeTextMeta,
	"before:top-1/2": sx.beforeTop12,
	"before:transition-[background]": sx.beforeTransitionBackground,
	"before:transition-colors": sx.beforeTransitionColors,
	"before:transition-opacity": sx.beforeTransitionOpacity,
	"before:z-0": sx.beforeZ0,
	"bg-[color-mix(in_srgb,var(--accent)_12%,transparent)]": sx.bgColorMixInSrgbVarAccent12Transparent,
	"bg-[color-mix(in_srgb,var(--accent)_16%,transparent)]": sx.bgColorMixInSrgbVarAccent16Transparent,
	"bg-[color-mix(in_srgb,var(--bg)_72%,transparent)]": sx.bgColorMixInSrgbVarBg72Transparent,
	"bg-[color-mix(in_srgb,var(--bg)_92%,transparent)]": sx.bgColorMixInSrgbVarBg92Transparent,
	"bg-[color-mix(in_srgb,var(--bg-panel)_68%,transparent)]": sx.bgColorMixInSrgbVarBgPanel68Transparent,
	"bg-[color-mix(in_srgb,var(--bg-panel)_80%,var(--composer-surface))]": sx.bgColorMixInSrgbVarBgPanel80VarComposerSurface,
	"bg-[color-mix(in_srgb,var(--yellow)_16%,transparent)]": sx.bgColorMixInSrgbVarYellow16Transparent,
	"bg-[var(--bg-hover)]": sx.bgVarBgHover,
	"bg-[var(--composer-surface)]": sx.bgVarComposerSurface,
	"bg-accent": sx.bgAccent,
	"bg-accent-soft": sx.bgAccentSoft,
	"bg-active": sx.bgActive,
	"bg-bg": sx.bgBg,
	"bg-bg/65": sx.bgBg65,
	"bg-bg/85": sx.bgBg85,
	"bg-black/45": sx.bgBlack45,
	"bg-black/50": sx.bgBlack50,
	"bg-blue": sx.bgBlue,
	"bg-blue-soft": sx.bgBlueSoft,
	"bg-clip-text": sx.bgClipText,
	"bg-dim/35": sx.bgDim35,
	"bg-divider": sx.bgDivider,
	"bg-faint": sx.bgFaint,
	"bg-faint/10": sx.bgFaint10,
	"bg-faint/35": sx.bgFaint35,
	"bg-fg": sx.bgFg,
	"bg-fg/15": sx.bgFg15,
	"bg-fg/45": sx.bgFg45,
	"bg-green": sx.bgGreen,
	"bg-green-soft": sx.bgGreenSoft,
	"bg-hover": sx.bgHover,
	"bg-hover/50": sx.bgHover50,
	"bg-line": sx.bgLine,
	"bg-palette-glass": sx.bgPaletteGlass,
	"bg-panel": sx.bgPanel,
	"bg-popup": sx.bgPopup,
	"bg-popup-glass": sx.bgPopupGlass,
	"bg-pressed": sx.bgPressed,
	"bg-raised": sx.bgRaised,
	"bg-red": sx.bgRed,
	"bg-red-soft": sx.bgRedSoft,
	"bg-selected": sx.bgSelected,
	"bg-settings-plate": sx.bgSettingsPlate,
	"bg-sidebar": sx.bgSidebar,
	"bg-surface": sx.bgSurface,
	"bg-transparent": sx.bgTransparent,
	"bg-yellow": sx.bgYellow,
	"block": sx.block,
	"border": sx.border,
	"border-0": sx.border0,
	"border-[color-mix(in_srgb,var(--accent)_40%,transparent)]": sx.borderColorMixInSrgbVarAccent40Transparent,
	"border-[color:color-mix(in_srgb,var(--composer-border)_35%,transparent)]": sx.borderColorColorMixInSrgbVarComposerBorder35Transparent,
	"border-[color:var(--composer-border)]": sx.borderColorVarComposerBorder,
	"border-[color:var(--mobile-header-control-border)]": sx.borderColorVarMobileHeaderControlBorder,
	"border-[rgba(13,148,136,0.5)]": sx.borderRgba1314813605,
	"border-[rgba(94,106,210,0.5)]": sx.borderRgba9410621005,
	"border-[var(--accent,#6b8afd)]": sx.borderVarAccent6b8afd,
	"border-accent": sx.borderAccent,
	"border-b": sx.borderB,
	"border-bg": sx.borderBg,
	"border-current/25": sx.borderCurrent25,
	"border-divider": sx.borderDivider,
	"border-divider-soft": sx.borderDividerSoft,
	"border-l": sx.borderL,
	"border-line": sx.borderLine,
	"border-line-strong": sx.borderLineStrong,
	"border-none": sx.borderNone,
	"border-r": sx.borderR,
	"border-t": sx.borderT,
	"border-t-current": sx.borderTCurrent,
	"border-transparent": sx.borderTransparent,
	"border-x": sx.borderX,
	"bottom-0": sx.bottom0,
	"bottom-2": sx.bottom2,
	"bottom-[124px]": sx.bottom124px,
	"bottom-[72px]": sx.bottom72px,
	"bottom-[calc(100%+6px)]": sx.bottomCalc1006px,
	"bottom-[calc(24px+var(--suggestions-under,0px))]": sx.bottomCalc24pxVarSuggestionsUnder0px,
	"bottom-[max(12px,env(safe-area-inset-bottom,0px))]": sx.bottomMax12pxEnvSafeAreaInsetBottom0px,
	"bottom-full": sx.bottomFull,
	"break-all": sx.breakAll,
	"break-words": sx.breakWords,
	"caret-[var(--text)]": sx.caretVarText,
	"contents": sx.contents,
	"cursor-col-resize": sx.cursorColResize,
	"cursor-default": sx.cursorDefault,
	"cursor-grab": sx.cursorGrab,
	"cursor-pointer": sx.cursorPointer,
	"cursor-text": sx.cursorText,
	"desktop:-mt-[11px]": sx.desktopMt11px,
	"desktop:border-transparent": sx.desktopBorderTransparent,
	"desktop:col-span-2": sx.desktopColSpan2,
	"desktop:col-start-1": sx.desktopColStart1,
	"desktop:col-start-2": sx.desktopColStart2,
	"desktop:contents": sx.desktopContents,
	"desktop:flex": sx.desktopFlex,
	"desktop:gap-10": sx.desktopGap10,
	"desktop:gap-[9px]": sx.desktopGap9px,
	"desktop:grid": sx.desktopGrid,
	"desktop:grid-cols-3": sx.desktopGridCols3,
	"desktop:grid-cols-4": sx.desktopGridCols4,
	"desktop:grid-cols-[3fr_2fr]": sx.desktopGridCols3fr2fr,
	"desktop:grid-cols-[minmax(0,1fr)_13rem]": sx.desktopGridColsMinmax01fr13rem,
	"desktop:grid-cols-[minmax(0,1fr)_auto_minmax(0,1fr)]": sx.desktopGridColsMinmax01frAutoMinmax01fr,
	"desktop:grid-cols-[minmax(0,720px)_220px]": sx.desktopGridColsMinmax0720px220px,
	"desktop:grid-cols-[repeat(auto-fit,200px)]": sx.desktopGridColsRepeatAutoFit200px,
	"desktop:h-[22rem]": sx.desktopH22rem,
	"desktop:h-[var(--sidebar-band-slot)]": sx.desktopHVarSidebarBandSlot,
	"desktop:h-[var(--sidebar-cap-h)]": sx.desktopHVarSidebarCapH,
	"desktop:h-[var(--sidebar-line-h)]": sx.desktopHVarSidebarLineH,
	"desktop:h-full": sx.desktopHFull,
	"desktop:hidden": sx.desktopHidden,
	"desktop:inline-flex": sx.desktopInlineFlex,
	"desktop:items-center": sx.desktopItemsCenter,
	"desktop:min-h-0": sx.desktopMinH0,
	"desktop:min-h-60": sx.desktopMinH60,
	"desktop:min-h-[var(--sidebar-band-slot)]": sx.desktopMinHVarSidebarBandSlot,
	"desktop:min-h-[var(--sidebar-cap-h)]": sx.desktopMinHVarSidebarCapH,
	"desktop:min-h-[var(--sidebar-line-h)]": sx.desktopMinHVarSidebarLineH,
	"desktop:min-w-[34px]": sx.desktopMinW34px,
	"desktop:ml-0": sx.desktopMl0,
	"desktop:mr-3.5": sx.desktopMr35,
	"desktop:mr-[312px]": sx.desktopMr312px,
	"desktop:mr-[320px]": sx.desktopMr320px,
	"desktop:mt-0": sx.desktopMt0,
	"desktop:mx-[var(--sidebar-nav-x)]": sx.desktopMxVarSidebarNavX,
	"desktop:pb-1": sx.desktopPb1,
	"desktop:pb-5": sx.desktopPb5,
	"desktop:pl-0": sx.desktopPl0,
	"desktop:pl-[calc(var(--sidebar-icon-left,16px)-var(--sidebar-nav-x,6px))]": sx.desktopPlCalcVarSidebarIconLeft16pxVarSidebarNavX6px,
	"desktop:pr-0": sx.desktopPr0,
	"desktop:pr-1": sx.desktopPr1,
	"desktop:pr-7": sx.desktopPr7,
	"desktop:pt-0.5": sx.desktopPt05,
	"desktop:pt-1": sx.desktopPt1,
	"desktop:pt-3": sx.desktopPt3,
	"desktop:px-5": sx.desktopPx5,
	"desktop:px-[var(--sidebar-nav-x)]": sx.desktopPxVarSidebarNavX,
	"desktop:py-0": sx.desktopPy0,
	"desktop:row-start-1": sx.desktopRowStart1,
	"desktop:row-start-2": sx.desktopRowStart2,
	"desktop:row-start-3": sx.desktopRowStart3,
	"desktop:size-[200px]": sx.desktopSize200px,
	"desktop:smooth-shadow-ring-soft": sx.desktopSmoothShadowRingSoft,
	"desktop:sticky": sx.desktopSticky,
	"desktop:text-item-title": sx.desktopTextItemTitle,
	"desktop:top-0": sx.desktopTop0,
	"desktop:top-[calc(var(--sidebar-band-slot)+var(--sidebar-line-h))]": sx.desktopTopCalcVarSidebarBandSlotVarSidebarLineH,
	"desktop:top-[var(--sidebar-band-slot)]": sx.desktopTopVarSidebarBandSlot,
	"desktop:w-full": sx.desktopWFull,
	"desktop:z-20": sx.desktopZ20,
	"desktop:z-[14]": sx.desktopZ14,
	"desktop:z-[15]": sx.desktopZ15,
	"disabled:cursor-default": sx.disabledCursorDefault,
	"disabled:opacity-100": sx.disabledOpacity100,
	"disabled:opacity-35": sx.disabledOpacity35,
	"disabled:opacity-70": sx.disabledOpacity70,
	"disabled:pointer-events-none": sx.disabledPointerEventsNone,
	"duration-(--dur)": sx.durationDur,
	"duration-(--dur-micro)": sx.durationDurMicro,
	"duration-150": sx.duration150,
	"duration-300": sx.duration300,
	"duration-[var(--dur)]": sx.durationVarDur,
	"duration-[var(--dur-lg)]": sx.durationVarDurLg,
	"duration-[var(--dur-micro)]": sx.durationVarDurMicro,
	"ease-(--ease)": sx.easeEase,
	"ease-[var(--ease)]": sx.easeVarEase,
	"fixed": sx.fixed,
	"flex": sx.flex,
	"flex-1": sx.flex1,
	"flex-[0_0_22px]": sx.flex0022px,
	"flex-[0_0_340px]": sx.flex00340px,
	"flex-[0_0_auto]": sx.flex00Auto,
	"flex-[0_1_auto]": sx.flex01Auto,
	"flex-auto": sx.flexAuto,
	"flex-col": sx.flexCol,
	"flex-none": sx.flexNone,
	"flex-shrink-0": sx.flexShrink0,
	"flex-wrap": sx.flexWrap,
	"focus-visible:after:border-line-strong": sx.focusVisibleAfterBorderLineStrong,
	"focus-visible:opacity-100": sx.focusVisibleOpacity100,
	"focus-visible:outline-fg": sx.focusVisibleOutlineFg,
	"focus-visible:outline-offset-2": sx.focusVisibleOutlineOffset2,
	"focus-visible:ring-[var(--accent,#6b8afd)]": sx.focusVisibleRingVarAccent6b8afd,
	"focus-visible:ring-accent/50": sx.focusVisibleRingAccent50,
	"focus-visible:ring-inset": sx.focusVisibleRingInset,
	"focus:border-transparent": sx.focusBorderTransparent,
	"font-[inherit]": sx.fontInherit,
	"font-bold": sx.fontBold,
	"font-medium": sx.fontMedium,
	"font-mono": sx.fontMono,
	"font-semibold": sx.fontSemibold,
	"gap-0": sx.gap0,
	"gap-0.5": sx.gap05,
	"gap-1": sx.gap1,
	"gap-1.5": sx.gap15,
	"gap-2": sx.gap2,
	"gap-2.5": sx.gap25,
	"gap-3": sx.gap3,
	"gap-3.5": sx.gap35,
	"gap-4": sx.gap4,
	"gap-[5px]": sx.gap5px,
	"gap-[7px]": sx.gap7px,
	"gap-[9px]": sx.gap9px,
	"gap-px": sx.gapPx,
	"gap-x-1": sx.gapX1,
	"gap-x-2": sx.gapX2,
	"gap-x-3": sx.gapX3,
	"gap-x-4": sx.gapX4,
	"gap-y-1": sx.gapY1,
	"gap-y-1.5": sx.gapY15,
	"gap-y-2.5": sx.gapY25,
	"grid": sx.grid,
	"grid-cols-1": sx.gridCols1,
	"grid-cols-2": sx.gridCols2,
	"grid-cols-6": sx.gridCols6,
	"grid-cols-[24px_minmax(0,1fr)]": sx.gridCols24pxMinmax01fr,
	"grid-cols-[minmax(0,1fr)_5.75rem]": sx.gridColsMinmax01fr575rem,
	"grid-cols-[minmax(0,1fr)_auto]": sx.gridColsMinmax01frAuto,
	"grid-cols-[minmax(0,300px)_minmax(0,1fr)]": sx.gridColsMinmax0300pxMinmax01fr,
	"grid-rows-[44px_minmax(0,1fr)]": sx.gridRows44pxMinmax01fr,
	"h-11": sx.h11,
	"h-12": sx.h12,
	"h-12!": sx.h122,
	"h-2": sx.h2,
	"h-2.5": sx.h25,
	"h-4": sx.h4,
	"h-7": sx.h7,
	"h-8": sx.h8,
	"h-[100dvh]": sx.h100dvh,
	"h-[18px]": sx.h18px,
	"h-[22px]": sx.h22px,
	"h-[31px]": sx.h31px,
	"h-[34px]": sx.h34px,
	"h-[52px]": sx.h52px,
	"h-[94dvh]": sx.h94dvh,
	"h-[min(500px,76vh)]": sx.hMin500px76vh,
	"h-[min(820px,85vh)]": sx.hMin820px85vh,
	"h-[min(840px,calc(100dvh-32px))]": sx.hMin840pxCalc100dvh32px,
	"h-[var(--desktop-header-h)]": sx.hVarDesktopHeaderH,
	"h-full": sx.hFull,
	"hidden": sx.hidden,
	"hover:after:bg-line-strong": sx.hoverAfterBgLineStrong,
	"hover:after:border-line-strong": sx.hoverAfterBorderLineStrong,
	"hover:before:bg-hover": sx.hoverBeforeBgHover,
	"hover:before:bg-pressed": sx.hoverBeforeBgPressed,
	"hover:bg-[image:linear-gradient(var(--hover),var(--hover))]": sx.hoverBgImageLinearGradientVarHoverVarHover,
	"hover:bg-[var(--row-chip)]": sx.hoverBgVarRowChip,
	"hover:bg-fg/85": sx.hoverBgFg85,
	"hover:bg-hover": sx.hoverBgHover,
	"hover:bg-hover/40": sx.hoverBgHover40,
	"hover:bg-panel": sx.hoverBgPanel,
	"hover:border-line-strong": sx.hoverBorderLineStrong,
	"hover:border-transparent": sx.hoverBorderTransparent,
	"hover:pr-[68px]": sx.hoverPr68px,
	"hover:scale-110": sx.hoverScale110,
	"hover:text-dim": sx.hoverTextDim,
	"hover:text-fg": sx.hoverTextFg,
	"hover:text-green": sx.hoverTextGreen,
	"hover:text-red": sx.hoverTextRed,
	"hover:underline": sx.hoverUnderline,
	"inline-flex": sx.inlineFlex,
	"inset-0": sx.inset0,
	"inset-x-0": sx.insetX0,
	"invisible": sx.invisible,
	"isolate": sx.isolate,
	"items-center": sx.itemsCenter,
	"items-start": sx.itemsStart,
	"items-stretch": sx.itemsStretch,
	"justify-between": sx.justifyBetween,
	"justify-center": sx.justifyCenter,
	"justify-end": sx.justifyEnd,
	"justify-self-center": sx.justifySelfCenter,
	"justify-start": sx.justifyStart,
	"leading-4": sx.leading4,
	"leading-[1.2]": sx.leading12,
	"leading-[1.45]": sx.leading145,
	"leading-[1.55]": sx.leading155,
	"leading-[52px]": sx.leading52px,
	"leading-none": sx.leadingNone,
	"left-0": sx.left0,
	"left-1/2": sx.left12,
	"left-14": sx.left14,
	"left-2": sx.left2,
	"left-3": sx.left3,
	"left-[calc(-1*var(--composer-inset-left,17px))]": sx.leftCalc1VarComposerInsetLeft17px,
	"line-clamp-4": sx.lineClamp4,
	"m-0": sx.m0,
	"max-[560px]:h-[min(560px,82vh)]": sx.max560pxHMin560px82vh,
	"max-[560px]:hidden": sx.max560pxHidden,
	"max-[560px]:mb-4": sx.max560pxMb4,
	"max-[560px]:pb-12": sx.max560pxPb12,
	"max-[560px]:pt-[18px]": sx.max560pxPt18px,
	"max-[560px]:px-4": sx.max560pxPx4,
	"max-[900px]:border-l-0": sx.max900pxBorderL0,
	"max-[900px]:hidden": sx.max900pxHidden,
	"max-[900px]:inline-flex": sx.max900pxInlineFlex,
	"max-h-[320px]": sx.maxH320px,
	"max-h-[calc(100dvh-32px)]": sx.maxHCalc100dvh32px,
	"max-h-[min(72vh,640px)]": sx.maxHMin72vh640px,
	"max-h-full": sx.maxHFull,
	"max-h-none": sx.maxHNone,
	"max-sm:grid-cols-1": sx.maxSmGridCols1,
	"max-sm:min-h-10": sx.maxSmMinH10,
	"max-sm:min-w-[55%]": sx.maxSmMinW55,
	"max-w-[1040px]": sx.maxW1040px,
	"max-w-[1160px]": sx.maxW1160px,
	"max-w-[240px]": sx.maxW240px,
	"max-w-[25rem]": sx.maxW25rem,
	"max-w-[280px]": sx.maxW280px,
	"max-w-[30rem]": sx.maxW30rem,
	"max-w-[31rem]": sx.maxW31rem,
	"max-w-[32rem]": sx.maxW32rem,
	"max-w-[34rem]": sx.maxW34rem,
	"max-w-[40rem]": sx.maxW40rem,
	"max-w-[420px]": sx.maxW420px,
	"max-w-[48rem]": sx.maxW48rem,
	"max-w-[720px]": sx.maxW720px,
	"max-w-[750px]": sx.maxW750px,
	"max-w-[780px]": sx.maxW780px,
	"max-w-[880px]": sx.maxW880px,
	"max-w-[calc(100vw-16px)]": sx.maxWCalc100vw16px,
	"max-w-[calc(var(--session-col)+40px)]": sx.maxWCalcVarSessionCol40px,
	"max-w-[min(320px,calc(100vw-1rem))]": sx.maxWMin320pxCalc100vw1rem,
	"max-w-[min(360px,calc(100vw-1rem))]": sx.maxWMin360pxCalc100vw1rem,
	"max-w-full": sx.maxWFull,
	"max-w-none": sx.maxWNone,
	"mb-0.5": sx.mb05,
	"mb-1": sx.mb1,
	"mb-2": sx.mb2,
	"mb-3": sx.mb3,
	"mb-4": sx.mb4,
	"mb-5": sx.mb5,
	"mb-[var(--sidebar-group-gap)]": sx.mbVarSidebarGroupGap,
	"md:ml-4": sx.mdMl4,
	"md:mr-2": sx.mdMr2,
	"md:opacity-0": sx.mdOpacity0,
	"min-h-0": sx.minH0,
	"min-h-10": sx.minH10,
	"min-h-11": sx.minH11,
	"min-h-12!": sx.minH12,
	"min-h-20": sx.minH20,
	"min-h-28": sx.minH28,
	"min-h-6": sx.minH6,
	"min-h-8": sx.minH8,
	"min-h-[320px]": sx.minH320px,
	"min-h-[38px]": sx.minH38px,
	"min-h-[calc(13px*1.45)]": sx.minHCalc13px145,
	"min-h-[calc(env(safe-area-inset-top,0px)+52px)]": sx.minHCalcEnvSafeAreaInsetTop0px52px,
	"min-h-[var(--sidebar-cap-h)]": sx.minHVarSidebarCapH,
	"min-w-0": sx.minW0,
	"min-w-4": sx.minW4,
	"min-w-[172px]": sx.minW172px,
	"min-w-[18px]": sx.minW18px,
	"min-w-[220px]": sx.minW220px,
	"min-w-[28px]": sx.minW28px,
	"min-w-[34px]": sx.minW34px,
	"ml-0": sx.ml0,
	"ml-1.5": sx.ml15,
	"ml-4": sx.ml4,
	"ml-[5px]": sx.ml5px,
	"ml-auto": sx.mlAuto,
	"motion-reduce:[animation-duration:1.2s]!": sx.motionReduceAnimationDuration12s,
	"motion-reduce:[animation-duration:1.4s]!": sx.motionReduceAnimationDuration14s,
	"motion-reduce:[animation-iteration-count:infinite]!": sx.motionReduceAnimationIterationCountInfinite,
	"motion-reduce:animate-none": sx.motionReduceAnimateNone,
	"motion-reduce:transform-none": sx.motionReduceTransformNone,
	"motion-reduce:transition-none": sx.motionReduceTransitionNone,
	"motion-safe:animate-pulse": sx.motionSafeAnimatePulse,
	"motion-safe:duration-150": sx.motionSafeDuration150,
	"motion-safe:transition-opacity": sx.motionSafeTransitionOpacity,
	"mr-1.5": sx.mr15,
	"mt-0": sx.mt0,
	"mt-0.5": sx.mt05,
	"mt-1": sx.mt1,
	"mt-2": sx.mt2,
	"mt-2.5": sx.mt25,
	"mt-3": sx.mt3,
	"mt-4": sx.mt4,
	"mt-9": sx.mt9,
	"mt-[9px]": sx.mt9px,
	"mt-[calc(-1*var(--session-under))]": sx.mtCalc1VarSessionUnder,
	"mx-1.5": sx.mx15,
	"mx-2": sx.mx2,
	"mx-3": sx.mx3,
	"mx-3.5": sx.mx35,
	"mx-auto": sx.mxAuto,
	"my-[-2px]": sx.my2px,
	"no-underline": sx.noUnderline,
	"object-cover": sx.objectCover,
	"opacity-0": sx.opacity0,
	"opacity-100": sx.opacity100,
	"opacity-40": sx.opacity40,
	"opacity-55": sx.opacity55,
	"opacity-60": sx.opacity60,
	"opacity-85": sx.opacity85,
	"order-1": sx.order1,
	"order-2": sx.order2,
	"order-3": sx.order3,
	"order-4": sx.order4,
	"order-5": sx.order5,
	"outline-divider": sx.outlineDivider,
	"outline-none": sx.outlineNone,
	"overflow-hidden": sx.overflowHidden,
	"overflow-x-auto": sx.overflowXAuto,
	"overflow-x-hidden": sx.overflowXHidden,
	"overflow-y-auto": sx.overflowYAuto,
	"overflow-y-hidden": sx.overflowYHidden,
	"overflow-y-visible": sx.overflowYVisible,
	"overscroll-contain": sx.overscrollContain,
	"p-0": sx.p0,
	"p-1": sx.p1,
	"p-2": sx.p2,
	"p-5": sx.p5,
	"p-6": sx.p6,
	"pb-0": sx.pb0,
	"pb-0.5": sx.pb05,
	"pb-1": sx.pb1,
	"pb-1.5": sx.pb15,
	"pb-10": sx.pb10,
	"pb-12": sx.pb12,
	"pb-2": sx.pb2,
	"pb-2.5": sx.pb25,
	"pb-22": sx.pb22,
	"pb-3.5": sx.pb35,
	"pb-5": sx.pb5,
	"pb-7": sx.pb7,
	"pb-[26px]": sx.pb26px,
	"pb-[5px]": sx.pb5px,
	"pb-[calc(var(--session-under)_+_var(--suggestions-under,0px)_+_16px)]": sx.pbCalcVarSessionUnderVarSuggestionsUnder0px16px,
	"pb-[max(16px,env(safe-area-inset-bottom,0px))]": sx.pbMax16pxEnvSafeAreaInsetBottom0px,
	"pb-[max(24px,env(safe-area-inset-bottom,0px))]": sx.pbMax24pxEnvSafeAreaInsetBottom0px,
	"phone:before:-inset-x-3": sx.phoneBeforeInsetX3,
	"phone:before:-top-1.5": sx.phoneBeforeTop15,
	"phone:bg-clip-content": sx.phoneBgClipContent,
	"phone:border-l-0": sx.phoneBorderL0,
	"phone:border-t": sx.phoneBorderT,
	"phone:bottom-auto": sx.phoneBottomAuto,
	"phone:col-start-2": sx.phoneColStart2,
	"phone:col-start-3": sx.phoneColStart3,
	"phone:duration-[var(--dur-lg)]": sx.phoneDurationVarDurLg,
	"phone:ease-[var(--ease)]": sx.phoneEaseVarEase,
	"phone:flex": sx.phoneFlex,
	"phone:flex-col": sx.phoneFlexCol,
	"phone:flex-col-reverse": sx.phoneFlexColReverse,
	"phone:gap-1.5": sx.phoneGap15,
	"phone:gap-2": sx.phoneGap2,
	"phone:gap-3": sx.phoneGap3,
	"phone:gap-x-2": sx.phoneGapX2,
	"phone:gap-y-0": sx.phoneGapY0,
	"phone:grid-cols-1": sx.phoneGridCols1,
	"phone:grid-cols-2": sx.phoneGridCols2,
	"phone:grid-cols-[minmax(0,1fr)_72px_minmax(38px,auto)]": sx.phoneGridColsMinmax01fr72pxMinmax38pxAuto,
	"phone:h-11": sx.phoneH11,
	"phone:h-full": sx.phoneHFull,
	"phone:hidden": sx.phoneHidden,
	"phone:inline": sx.phoneInline,
	"phone:inline-flex": sx.phoneInlineFlex,
	"phone:inset-x-0": sx.phoneInsetX0,
	"phone:items-center": sx.phoneItemsCenter,
	"phone:items-start": sx.phoneItemsStart,
	"phone:items-stretch": sx.phoneItemsStretch,
	"phone:justify-end": sx.phoneJustifyEnd,
	"phone:max-h-[240px]": sx.phoneMaxH240px,
	"phone:max-h-none": sx.phoneMaxHNone,
	"phone:max-w-[136px]": sx.phoneMaxW136px,
	"phone:max-w-none": sx.phoneMaxWNone,
	"phone:mb-6": sx.phoneMb6,
	"phone:min-h-0": sx.phoneMinH0,
	"phone:min-h-10": sx.phoneMinH10,
	"phone:min-h-11": sx.phoneMinH11,
	"phone:min-h-12": sx.phoneMinH12,
	"phone:min-h-14": sx.phoneMinH14,
	"phone:ml-auto": sx.phoneMlAuto,
	"phone:mt-0": sx.phoneMt0,
	"phone:mt-1.5": sx.phoneMt15,
	"phone:my-3": sx.phoneMy3,
	"phone:order-[-1]": sx.phoneOrder1,
	"phone:order-[-2]": sx.phoneOrder2,
	"phone:overflow-visible": sx.phoneOverflowVisible,
	"phone:p-1": sx.phoneP1,
	"phone:p-3.5": sx.phoneP35,
	"phone:p-4": sx.phoneP4,
	"phone:p-5": sx.phoneP5,
	"phone:p-6": sx.phoneP6,
	"phone:pb-0": sx.phonePb0,
	"phone:pb-1": sx.phonePb1,
	"phone:pb-12": sx.phonePb12,
	"phone:pb-[9px]": sx.phonePb9px,
	"phone:pb-[max(12px,env(safe-area-inset-bottom))]": sx.phonePbMax12pxEnvSafeAreaInsetBottom,
	"phone:pb-[max(16px,env(safe-area-inset-bottom,0px))]": sx.phonePbMax16pxEnvSafeAreaInsetBottom0px,
	"phone:pl-2": sx.phonePl2,
	"phone:pl-3.5": sx.phonePl35,
	"phone:pl-[10px]": sx.phonePl10px,
	"phone:pl-[17px]": sx.phonePl17px,
	"phone:pr-0": sx.phonePr0,
	"phone:pr-0.5": sx.phonePr05,
	"phone:pt-0": sx.phonePt0,
	"phone:pt-2.5": sx.phonePt25,
	"phone:pt-3": sx.phonePt3,
	"phone:pt-4": sx.phonePt4,
	"phone:pt-5": sx.phonePt5,
	"phone:pt-6": sx.phonePt6,
	"phone:pt-[calc(var(--pane-header-h)+var(--strip-clearance,0px))]": sx.phonePtCalcVarPaneHeaderHVarStripClearance0px,
	"phone:pt-[calc(var(--pane-header-h)+var(--strip-clearance,0px)+8px)]": sx.phonePtCalcVarPaneHeaderHVarStripClearance0px8px,
	"phone:pt-[max(12px,env(safe-area-inset-top))]": sx.phonePtMax12pxEnvSafeAreaInsetTop,
	"phone:px-0": sx.phonePx0,
	"phone:px-2": sx.phonePx2,
	"phone:px-3": sx.phonePx3,
	"phone:px-4": sx.phonePx4,
	"phone:px-5": sx.phonePx5,
	"phone:px-[9px]": sx.phonePx9px,
	"phone:py-4": sx.phonePy4,
	"phone:py-[13px]": sx.phonePy13px,
	"phone:py-[7px]": sx.phonePy7px,
	"phone:right-0": sx.phoneRight0,
	"phone:rounded-lg": sx.phoneRoundedLg,
	"phone:rounded-none": sx.phoneRoundedNone,
	"phone:row-start-1": sx.phoneRowStart1,
	"phone:self-stretch": sx.phoneSelfStretch,
	"phone:size-10": sx.phoneSize10,
	"phone:size-11": sx.phoneSize11,
	"phone:text-base": sx.phoneTextBase,
	"phone:text-input-phone": sx.phoneTextInputPhone,
	"phone:text-label": sx.phoneTextLabel,
	"phone:text-section-title": sx.phoneTextSectionTitle,
	"phone:top-[calc(var(--header-h)+8px)]": sx.phoneTopCalcVarHeaderH8px,
	"phone:top-[calc(var(--pane-header-h)+var(--strip-clearance,0px)+8px)]": sx.phoneTopCalcVarPaneHeaderHVarStripClearance0px8px,
	"phone:w-9": sx.phoneW9,
	"phone:w-full": sx.phoneWFull,
	"phone:whitespace-normal": sx.phoneWhitespaceNormal,
	"pl-0": sx.pl0,
	"pl-0.5": sx.pl05,
	"pl-1.5": sx.pl15,
	"pl-2": sx.pl2,
	"pl-2.5": sx.pl25,
	"pl-3": sx.pl3,
	"pl-[19px]": sx.pl19px,
	"pl-[calc(var(--sidebar-icon-left)-8px)]": sx.plCalcVarSidebarIconLeft8px,
	"pl-[calc(var(--sidebar-icon-left,16px)-var(--sidebar-nav-x,6px))]": sx.plCalcVarSidebarIconLeft16pxVarSidebarNavX6px,
	"place-items-center": sx.placeItemsCenter,
	"placeholder:text-[color-mix(in_srgb,var(--text-faint)_84%,var(--yellow))]": sx.placeholderTextColorMixInSrgbVarTextFaint84VarYellow,
	"placeholder:text-faint": sx.placeholderTextFaint,
	"pointer-events-auto": sx.pointerEventsAuto,
	"pointer-events-none": sx.pointerEventsNone,
	"pr-0.5": sx.pr05,
	"pr-1": sx.pr1,
	"pr-1.5": sx.pr15,
	"pr-2": sx.pr2,
	"pr-3": sx.pr3,
	"pr-3.5": sx.pr35,
	"pr-5": sx.pr5,
	"pr-[26px]": sx.pr26px,
	"pr-[7px]": sx.pr7px,
	"pt-0": sx.pt0,
	"pt-0.5": sx.pt05,
	"pt-1": sx.pt1,
	"pt-11": sx.pt11,
	"pt-2": sx.pt2,
	"pt-2.5": sx.pt25,
	"pt-3": sx.pt3,
	"pt-3.5": sx.pt35,
	"pt-4": sx.pt4,
	"pt-5": sx.pt5,
	"pt-[9px]": sx.pt9px,
	"pt-[env(safe-area-inset-top,0px)]": sx.ptEnvSafeAreaInsetTop0px,
	"pt-[var(--header-h)]": sx.ptVarHeaderH,
	"pt-px": sx.ptPx,
	"px-0": sx.px0,
	"px-0.5": sx.px05,
	"px-1": sx.px1,
	"px-1.5": sx.px15,
	"px-10": sx.px10,
	"px-2": sx.px2,
	"px-2.5": sx.px25,
	"px-3": sx.px3,
	"px-3.5": sx.px35,
	"px-3.5!": sx.px352,
	"px-4": sx.px4,
	"px-5": sx.px5,
	"px-6": sx.px6,
	"px-8": sx.px8,
	"px-[11px]": sx.px11px,
	"px-[13px]": sx.px13px,
	"px-[16px]": sx.px16px,
	"px-[5px]": sx.px5px,
	"px-[6px]": sx.px6px,
	"px-[9px]": sx.px9px,
	"px-[calc(var(--sidebar-icon-left)-var(--sidebar-nav-x))]": sx.pxCalcVarSidebarIconLeftVarSidebarNavX,
	"px-[var(--sidebar-nav-x)]": sx.pxVarSidebarNavX,
	"py-0": sx.py0,
	"py-0.5": sx.py05,
	"py-1": sx.py1,
	"py-1.5": sx.py15,
	"py-2": sx.py2,
	"py-2.5": sx.py25,
	"py-3.5": sx.py35,
	"py-4": sx.py4,
	"py-[3px]": sx.py3px,
	"py-[5px]": sx.py5px,
	"py-[7px]": sx.py7px,
	"py-[9px]": sx.py9px,
	"py-[var(--sidebar-tool-pad)]": sx.pyVarSidebarToolPad,
	"py-px": sx.pyPx,
	"relative": sx.relative,
	"resize-none": sx.resizeNone,
	"resize-y": sx.resizeY,
	"right-0": sx.right0,
	"right-14": sx.right14,
	"right-3": sx.right3,
	"right-4": sx.right4,
	"right-[-3px]": sx.right3px,
	"right-[5px]": sx.right5px,
	"right-[7px]": sx.right7px,
	"rotate-180": sx.rotate180,
	"rounded-2xl": sx.rounded2xl,
	"rounded-[999px]": sx.rounded999px,
	"rounded-[calc(6px*var(--rf))]": sx.roundedCalc6pxVarRf,
	"rounded-[calc(8px*var(--rf))]": sx.roundedCalc8pxVarRf,
	"rounded-[var(--composer-radius)]": sx.roundedVarComposerRadius,
	"rounded-control": sx.roundedControl,
	"rounded-full": sx.roundedFull,
	"rounded-lg": sx.roundedLg,
	"rounded-md": sx.roundedMd,
	"rounded-row": sx.roundedRow,
	"rounded-section": sx.roundedSection,
	"rounded-sm": sx.roundedSm,
	"rounded-t-[var(--composer-radius)]": sx.roundedTVarComposerRadius,
	"rounded-xl": sx.roundedXl,
	"scroll-mt-4": sx.scrollMt4,
	"select-all": sx.selectAll,
	"select-none": sx.selectNone,
	"select-text": sx.selectText,
	"self-center": sx.selfCenter,
	"self-start": sx.selfStart,
	"self-stretch": sx.selfStretch,
	"shrink": sx.shrink,
	"shrink-0": sx.shrink0,
	"size-1.5": sx.size15,
	"size-10": sx.size10,
	"size-11": sx.size11,
	"size-14": sx.size14,
	"size-16": sx.size16,
	"size-3": sx.size3,
	"size-4": sx.size4,
	"size-5": sx.size5,
	"size-7": sx.size7,
	"size-8": sx.size8,
	"size-9": sx.size9,
	"size-[18px]": sx.size18px,
	"size-[22px]": sx.size22px,
	"size-[34px]": sx.size34px,
	"size-[38px]": sx.size38px,
	"size-[7px]": sx.size7px,
	"size-full": sx.sizeFull,
	"sm:grid-cols-2": sx.smGridCols2,
	"snap-start": sx.snapStart,
	"sticky": sx.sticky,
	"text-[#17130a]": sx.text17130a,
	"text-[#5eead4]": sx.text5eead4,
	"text-[#7b86e8]": sx.text7b86e8,
	"text-[10px]": sx.text10px,
	"text-[15px]": sx.text15px,
	"text-[20px]": sx.text20px,
	"text-[22px]": sx.text22px,
	"text-[color-mix(in_srgb,var(--text)_88%,#1f9e8a)]": sx.textColorMixInSrgbVarText881f9e8a,
	"text-[inherit]": sx.textInherit,
	"text-base!": sx.textBase,
	"text-bg": sx.textBg,
	"text-center": sx.textCenter,
	"text-dim": sx.textDim,
	"text-ellipsis": sx.textEllipsis,
	"text-fg": sx.textFg,
	"text-fg/65": sx.textFg65,
	"text-inherit": sx.textInherit2,
	"text-left": sx.textLeft,
	"text-on-accent": sx.textOnAccent,
	"text-panel": sx.textPanel,
	"text-red": sx.textRed,
	"text-right": sx.textRight,
	"text-transparent": sx.textTransparent,
	"text-white": sx.textWhite,
	"top-0": sx.top0,
	"top-1/2": sx.top12,
	"top-[calc((var(--desktop-header-h)-35px)/2)]": sx.topCalcVarDesktopHeaderH35px2,
	"top-[calc(var(--desktop-header-h)+8px)]": sx.topCalcVarDesktopHeaderH8px,
	"touch-none": sx.touchNone,
	"tracking-[-0.01em]": sx.tracking001em,
	"tracking-[-0.02em]": sx.tracking002em,
	"tracking-[0.02em]": sx.tracking002em2,
	"transform-[translateX(var(--swipe-x,0))]": sx.transformTranslateXVarSwipeX0,
	"transition-[background-color,border-color,color,filter,scale]": sx.transitionBackgroundColorBorderColorColorFilterScale,
	"transition-[background-color,color,scale]": sx.transitionBackgroundColorColorScale,
	"transition-[background-color,scale]": sx.transitionBackgroundColorScale,
	"transition-[background-color]": sx.transitionBackgroundColor,
	"transition-[border-color,box-shadow]": sx.transitionBorderColorBoxShadow,
	"transition-[border-color,scale]": sx.transitionBorderColorScale,
	"transition-[color,background-color,scale]": sx.transitionColorBackgroundColorScale,
	"transition-[color,background]": sx.transitionColorBackground,
	"transition-[color,opacity,background]": sx.transitionColorOpacityBackground,
	"transition-[color,scale]": sx.transitionColorScale,
	"transition-[opacity,color]": sx.transitionOpacityColor,
	"transition-[opacity,transform]": sx.transitionOpacityTransform,
	"transition-[scale]": sx.transitionScale,
	"transition-[transform,filter]": sx.transitionTransformFilter,
	"transition-[transform,opacity]": sx.transitionTransformOpacity,
	"transition-[width,background-color,opacity]": sx.transitionWidthBackgroundColorOpacity,
	"transition-[width,height]": sx.transitionWidthHeight,
	"transition-[width]": sx.transitionWidth,
	"transition-colors": sx.transitionColors,
	"transition-none": sx.transitionNone,
	"transition-opacity": sx.transitionOpacity,
	"transition-transform": sx.transitionTransform,
	"translate-x-[calc(-50%+var(--ws-summary-step,0px))]": sx.translateXCalc50VarWsSummaryStep0px,
	"truncate": sx.truncate,
	"visible": sx.visible,
	"w-2": sx.w2,
	"w-21": sx.w21,
	"w-5": sx.w5,
	"w-6": sx.w6,
	"w-7": sx.w7,
	"w-[140px]": sx.w140px,
	"w-[220px]": sx.w220px,
	"w-[300px]": sx.w300px,
	"w-[46px]": sx.w46px,
	"w-[7px]": sx.w7px,
	"w-[calc((100%_-_30px)/2)]": sx.wCalc10030px2,
	"w-[calc(100%+12px)]": sx.wCalc10012px,
	"w-[calc(100%_-_16px)]": sx.wCalc10016px,
	"w-[min(1040px,calc(100vw-32px))]": sx.wMin1040pxCalc100vw32px,
	"w-[min(1280px,92vw)]": sx.wMin1280px92vw,
	"w-[min(640px,100%)]": sx.wMin640px100,
	"w-[min(880px,calc(100vw-32px))]": sx.wMin880pxCalc100vw32px,
	"w-[var(--sidebar-w,280px)]": sx.wVarSidebarW280px,
	"w-[var(--swipe-action-w,82px)]": sx.wVarSwipeActionW82px,
	"w-auto": sx.wAuto,
	"w-fit": sx.wFit,
	"w-full": sx.wFull,
	"w-full!": sx.wFull2,
	"whitespace-nowrap": sx.whitespaceNowrap,
	"whitespace-pre-wrap": sx.whitespacePreWrap,
	"will-change-[width]": sx.willChangeWidth,
	"will-change-transform": sx.willChangeTransform,
	"z-0": sx.z0,
	"z-1": sx.z1,
	"z-10": sx.z10,
	"z-20": sx.z20,
	"z-30": sx.z30,
	"z-40": sx.z40,
	"z-[1]": sx.z12,
	"z-[200]": sx.z200,
	"z-[2147483646]": sx.z2147483646,
	"z-[4]": sx.z4,
	"z-[5]": sx.z5,
	"z-[60]": sx.z60,
	"z-[9500]": sx.z9500,
	"text-body": typography.body,
	"text-control-label": typography.controlLabel,
	"text-item-title": typography.itemTitle,
	"text-label": typography.label,
	"text-meta": typography.meta,
	"text-page-title": typography.pageTitle,
	"text-section-title": typography.sectionTitle,
	"text-supporting": typography.supporting,
} as const;
export type UtilityClass = keyof typeof utilityStyles;
