/**
 * Unified Agent Context: The single source of truth for what an agent knows.
 *
 * This is the centerpiece of PR7: agents don't individually construct context.
 * Mission Control assembles it from the repository graph (PR6), task state,
 * execution history, and durable conversation.
 *
 * Key principle: Relevance ranking prevents dumping the entire repository.
 */

import type { RepositoryGraphQueries } from "./repository-graph-queries";
import type { DurableConversationLedger } from "./durable-conversation-ledger";
import type { RepositoryFile } from "./durable-repository-file-registry";

export interface ProjectContext {
  projectId: string;
  projectName: string;
  description?: string;
  slackChannelId?: string;
}

export interface RepositoryContext {
  repositoryId: string;
  owner: string;
  name: string;
  remoteUrl: string;
  defaultBranch: string;
  headCommit: string;
  lastIndexedAt: string;
}

export interface FileContext {
  fileId: string;
  path: string;
  language?: string;
  sizeBytes: number;
  relevanceScore: number;
  reason: string;
  relatedSymbols?: Array<{ name: string; kind: string }>;
  dependencies: string[];
  dependents: string[];
}

export interface SymbolContext {
  symbolId: string;
  fileId: string;
  name: string;
  kind:
    | "module"
    | "class"
    | "function"
    | "method"
    | "type"
    | "interface"
    | "constant"
    | "variable"
    | "enum";
  relevanceScore: number;
  reason: string;
  references: Array<{ file: string; line: number }>;
}

export interface ChangeContext {
  fileId: string;
  path: string;
  changeType: "added" | "modified" | "deleted" | "renamed";
  commitSha: string;
  author?: string;
  message: string;
  commitDate: string;
}

export interface AttemptContext {
  attemptNumber: number;
  agentId: string;
  status: "success" | "failed" | "blocked";
  output: string;
  error?: string;
  duration: number;
  timestamp: string;
}

export interface DecisionContext {
  decisionId: string;
  agentId: string;
  decision: string;
  reasoning: string;
  confidence: number;
  timestamp: string;
}

export interface ReviewContext {
  reviewId: string;
  reviewer: string;
  status: "approved" | "requested_changes" | "commented";
  comments: string;
  timestamp: string;
}

export interface FailureContext {
  failureId: string;
  executionId: string;
  error: string;
  stackTrace?: string;
  timestamp: string;
}

export interface BlockerContext {
  blockerId: string;
  description: string;
  blockedBy: string;
  createdAt: string;
}

export interface AgentContextSummary {
  agentId: string;
  handle: string;
  displayName: string;
  role:
    | "architect"
    | "builder"
    | "reviewer"
    | "tester"
    | "release"
    | "github"
    | "local";
  capabilities: string[];
  currentStatus?: "idle" | "working" | "blocked";
}

export interface TaskContext {
  taskId: string;
  title: string;
  description: string;
  acceptanceCriteria: string[];
  priority: "low" | "medium" | "high" | "critical";
  status: "created" | "in_progress" | "blocked" | "completed" | "rejected";
  assignedTo?: string;
  createdAt: string;
}

export interface ExecutionContext {
  executionId: string;
  agentId: string;
  taskId: string;
  worktreeId?: string;
  status: "started" | "running" | "completed" | "failed";
  startedAt: string;
  completedAt?: string;
}

export interface ConversationContext {
  conversationId: string;
  projectId: string;
  taskId?: string;
  participants: string[];
  lastMessageAt: string;
  turnCount: number;
}

export interface AcceptanceCriterion {
  criterion: string;
  verified: boolean;
  evidence?: string;
}

export interface Constraint {
  description: string;
  category:
    | "performance"
    | "security"
    | "compatibility"
    | "policy"
    | "resource";
  severity: "low" | "medium" | "high" | "critical";
}

export interface ContextRelevance {
  sourceId: string;
  sourceType: "file" | "symbol" | "commit" | "decision" | "attempt" | "task";
  score: number;
  reason: string;
}

/**
 * The complete context an agent receives.
 * Generated by ContextEngine, consumed by agents.
 */
export interface UnifiedAgentContext {
  // Identity
  project: ProjectContext;
  repository: RepositoryContext;

  // Work scope
  task?: TaskContext;
  execution?: ExecutionContext;

  // Repository intelligence (from PR6)
  relevantFiles: FileContext[];
  relevantSymbols: SymbolContext[];
  recentChanges: ChangeContext[];

  // Execution history
  priorAttempts: AttemptContext[];
  decisions: DecisionContext[];
  reviews: ReviewContext[];
  failures: FailureContext[];

  // Blockers
  blockers: BlockerContext[];

  // Other agents
  relatedAgents: AgentContextSummary[];

  // Conversation history
  conversation: ConversationContext;

  // Work specification
  acceptanceCriteria: AcceptanceCriterion[];
  constraints: Constraint[];

  // Metadata
  generatedAt: string;
  relevanceInfo: ContextRelevance[];
}

/**
 * Context Engine configuration.
 * Specifies what to include, in what priority order.
 */
export interface ContextConfig {
  maxRelevantFiles: number;
  maxRelevantSymbols: number;
  maxRecentChanges: number;
  maxPriorAttempts: number;
  maxDecisions: number;
  maxReviews: number;
  recentChangesWindow: number; // days
  relevanceThreshold: number; // 0-100
}

export interface ContextEngine {
  /**
   * Build complete context for a task.
   * Called before agent starts work.
   */
  buildForTask(taskId: string, agentId: string): Promise<UnifiedAgentContext>;

  /**
   * Build context for an ongoing execution.
   * Called during agent handoffs.
   */
  buildForExecution(
    executionId: string,
    agentId: string
  ): Promise<UnifiedAgentContext>;

  /**
   * Build context from conversation.
   * Called for human-agent interactions.
   */
  buildForConversation(
    conversationId: string,
    agentId: string
  ): Promise<UnifiedAgentContext>;

  /**
   * Build context focused on a specific file.
   * Called for change risk analysis.
   */
  buildForFile(fileId: string, agentId: string): Promise<UnifiedAgentContext>;

  /**
   * Build context for entire repository.
   * Called for architecture reviews.
   */
  buildForRepository(
    repositoryId: string,
    agentId: string
  ): Promise<UnifiedAgentContext>;

  /**
   * Build context snapshot for reproducibility.
   * Saved with execution.
   */
  createContextSnapshot(
    context: UnifiedAgentContext,
    commitSha: string,
    graphVersion: number
  ): Promise<ContextSnapshot>;
}

/**
 * Context snapshot: what did the agent know when it worked?
 * Enables reproducibility and historical analysis.
 */
export interface ContextSnapshot {
  id: string;
  taskId: string;
  agentId: string;
  repositoryCommit: string;
  graphVersion: number;
  context: UnifiedAgentContext;
  createdAt: string;
}

/**
 * Agent memory: what did we learn?
 * Scoped to project/repository for reuse.
 */
export interface AgentMemory {
  id: string;
  agentId: string;
  projectId: string;
  repositoryId?: string;
  kind: "decision" | "lesson" | "failure" | "pattern" | "constraint" | "preference";
  content: string;
  sourceExecutionId?: string;
  sourceTaskId?: string;
  confidence: number;
  createdAt: string;
  updatedAt: string;
}

/**
 * Agent handoff: explicit transition between agents.
 * Replaces implicit "you're done, I'll take it from here".
 */
export interface AgentHandoff {
  id: string;
  projectId: string;
  taskId: string;
  fromAgentId: string;
  toAgentId: string;
  executionId: string;
  objective: string;
  context: UnifiedAgentContext;
  acceptanceCriteria: AcceptanceCriterion[];
  requestedAction: string;
  status: "pending" | "accepted" | "completed" | "rejected";
  createdAt: string;
  completedAt?: string;
}

/**
 * Evidence: the actual proof for an important claim.
 * Agents should always provide evidence, not just assertions.
 */
export interface Evidence {
  id: string;
  executionId: string;
  type: "test" | "build" | "lint" | "review" | "git" | "github";
  command?: string;
  result: string;
  exitCode?: number;
  artifactRef?: string;
  startedAt: string;
  completedAt: string;
}

/**
 * Agent question: agent needs human input to proceed.
 */
export interface AgentQuestion {
  id: string;
  taskId: string;
  executionId: string;
  fromAgentId: string;
  question: string;
  blocking: boolean;
  target: "human" | "architect" | "builder" | "reviewer" | "tester" | "github";
  status: "open" | "answered" | "cancelled";
  answer?: string;
  answeredBy?: string;
  createdAt: string;
  answeredAt?: string;
}
